BEGIN;

INSERT INTO sababuka.units (code, name, symbol, decimal_places)
VALUES
    ('PERCENT', 'Persen', '%', 2),
    ('NUMBER', 'Angka', NULL, 4),
    ('INDEX', 'Indeks', NULL, 4),
    ('RATING', 'Nilai/Predikat', NULL, 2),
    ('POINT', 'Poin', NULL, 4),
    ('IDR', 'Rupiah', 'Rp', 2),
    ('IDR_MILLION', 'Rupiah juta', 'Rp juta', 3),
    ('SCORE', 'Skor', NULL, 2),
    ('YEAR', 'Tahun', 'tahun', 2),
    ('PER_100K_LIVE_BIRTHS', 'Per 100.000 kelahiran hidup', 'per 100.000 KH', 2)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, symbol = EXCLUDED.symbol, decimal_places = EXCLUDED.decimal_places, is_active = true;

INSERT INTO sababuka.policy_focuses (code, name, description, display_order, is_active)
VALUES
    ('RPJMD_F1', 'Kapuas sebagai sentra pangan dan hilirisasi agro-perikanan', 'Usulan fokus kebijakan hasil pemetaan RPJMD; menunggu pengesahan Bapperida.', 10, true),
    ('RPJMD_F2', 'Investasi, industri, dan simpul logistik Batanjung', 'Usulan fokus kebijakan hasil pemetaan RPJMD; menunggu pengesahan Bapperida.', 20, true),
    ('RPJMD_F3', 'Membangun dari desa dan ekonomi rakyat', 'Usulan fokus kebijakan hasil pemetaan RPJMD; menunggu pengesahan Bapperida.', 30, true),
    ('RPJMD_F4', 'SDM berkualitas dan sejahtera', 'Usulan fokus kebijakan hasil pemetaan RPJMD; menunggu pengesahan Bapperida.', 40, true),
    ('RPJMD_F5', 'Konektivitas wilayah dan layanan dasar', 'Usulan fokus kebijakan hasil pemetaan RPJMD; menunggu pengesahan Bapperida.', 50, true),
    ('RPJMD_F6', 'Lingkungan, iklim, dan kebencanaan', 'Usulan fokus kebijakan hasil pemetaan RPJMD; menunggu pengesahan Bapperida.', 60, true),
    ('RPJMD_F7', 'Kapuas aman dan religius', 'Usulan fokus kebijakan hasil pemetaan RPJMD; menunggu pengesahan Bapperida.', 70, true),
    ('RPJMD_F8', 'Tata kelola digital, data, dan fiskal', 'Usulan fokus kebijakan hasil pemetaan RPJMD; menunggu pengesahan Bapperida.', 80, true)
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, display_order = EXCLUDED.display_order, is_active = true, archived_at = NULL;

INSERT INTO sababuka.categories (code, name, description, policy_focus_id, display_order, is_active)
SELECT v.code, v.name, v.description, pf.id, v.display_order, true
FROM (VALUES
    ('RPJMD_1_1', 'Ketersediaan dan diversifikasi pangan', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F1', 11),
    ('RPJMD_1_2', 'Produktivitas dan nilai tambah pertanian', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F1', 12),
    ('RPJMD_1_3', 'Hilirisasi perikanan', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F1', 13),
    ('RPJMD_1_4', 'Stabilitas harga pangan dan barang pokok', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F1', 14),
    ('RPJMD_2_1', 'Iklim dan daya tarik investasi', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F2', 21),
    ('RPJMD_2_2', 'Industrialisasi berbasis SDA lokal', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F2', 22),
    ('RPJMD_2_3', 'Pertumbuhan dan daya saing daerah', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F2', 23),
    ('RPJMD_2_4', 'Kawasan Industri dan Pelabuhan Bahaur-Batanjung', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F2', 24),
    ('RPJMD_3_1', 'Kemandirian desa', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F3', 31),
    ('RPJMD_3_2', 'UMKM, perdagangan, dan kewirausahaan', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F3', 32),
    ('RPJMD_3_3', 'Pariwisata dan ekonomi berbasis budaya', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F3', 33),
    ('RPJMD_4_1', 'Kesejahteraan, kemiskinan, dan ketenagakerjaan', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F4', 41),
    ('RPJMD_4_2', 'Kesehatan dan stunting', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F4', 42),
    ('RPJMD_4_3', 'Pendidikan dan literasi', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F4', 43),
    ('RPJMD_4_4', 'Keluarga, gender, dan perlindungan anak', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F4', 44),
    ('RPJMD_5_1', 'Konektivitas darat–sungai', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F5', 51),
    ('RPJMD_5_2', 'Air minum, sanitasi, dan drainase', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F5', 52),
    ('RPJMD_5_3', 'Permukiman layak', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F5', 53),
    ('RPJMD_6_1', 'Kualitas lingkungan hidup', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F6', 61),
    ('RPJMD_6_2', 'Iklim, ekonomi hijau, dan keanekaragaman hayati', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F6', 62),
    ('RPJMD_6_3', 'Pengurangan risiko bencana', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F6', 63),
    ('RPJMD_6_4', 'Pengendalian tata ruang', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F6', 64),
    ('RPJMD_7_1', 'Kerukunan dan kohesi sosial', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F7', 71),
    ('RPJMD_7_2', 'Pelestarian budaya', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F7', 72),
    ('RPJMD_7_3', 'Ketenteraman, ketertiban, dan proteksi kebakaran', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F7', 73),
    ('RPJMD_8_1', 'Reformasi birokrasi dan akuntabilitas', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F8', 81),
    ('RPJMD_8_2', 'Digitalisasi pemerintahan dan inovasi', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F8', 82),
    ('RPJMD_8_3', 'Pelayanan publik dan profesionalitas ASN', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F8', 83),
    ('RPJMD_8_4', 'Kemandirian dan akuntabilitas fiskal', 'Usulan kelompok isu RPJMD; menunggu pengesahan Bapperida.', 'RPJMD_F8', 84)
) AS v(code, name, description, focus_code, display_order)
JOIN sababuka.policy_focuses pf ON pf.code = v.focus_code
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, policy_focus_id = EXCLUDED.policy_focus_id, display_order = EXCLUDED.display_order, is_active = true, archived_at = NULL;

CREATE TEMP TABLE rpmd_indicator_drafts (code text, name text, category_code text, owner_code text, definition text, unit_code text, data_type text, direction text, source_reference text, dimension_schema jsonb) ON COMMIT DROP;
INSERT INTO rpmd_indicator_drafts VALUES
    ('IKP', 'Indeks Ketahanan Pangan (IKP)', 'RPJMD_1_1', 'DKPP', 'Definisi operasional Indeks Ketahanan Pangan (IKP) menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: Badan Pangan Nasional (rilis IKP)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F1","proposed_category_code":"RPJMD_1_1","rpjmd_level":"Tujuan","source_page":"III-19","source_data_proposal":"Badan Pangan Nasional (rilis IKP)","supporting_organizations_proposal":"Dinas Pertanian; Disperindagkop-UKM","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DKPP"}'::jsonb),
    ('PPH_KETERSEDIAAN', 'Skor Pola Pangan Harapan (PPH) Ketersediaan', 'RPJMD_1_1', 'DKPP', 'Definisi operasional Skor Pola Pangan Harapan (PPH) Ketersediaan menunggu verifikasi OPD pemilik.', 'SCORE', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: DKPP (Neraca Bahan Makanan)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F1","proposed_category_code":"RPJMD_1_1","rpjmd_level":"Sasaran","source_page":"III-19","source_data_proposal":"DKPP (Neraca Bahan Makanan)","supporting_organizations_proposal":"Dinas Pertanian","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DKPP"}'::jsonb),
    ('RPJMD_I007_SKOR_POLA_PANGAN_HARAPAN_PPH_KONSUMSI', 'Skor Pola Pangan Harapan (PPH) Konsumsi', 'RPJMD_1_1', 'DKPP', 'Definisi operasional Skor Pola Pangan Harapan (PPH) Konsumsi menunggu verifikasi OPD pemilik.', 'SCORE', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: DKPP (olah data Susenas BPS)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F1","proposed_category_code":"RPJMD_1_1","rpjmd_level":"Sasaran","source_page":"III-19","source_data_proposal":"DKPP (olah data Susenas BPS)","supporting_organizations_proposal":"Dinkes","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DKPP"}'::jsonb),
    ('RASIO_PDRB_PERTANIAN', 'Rasio PDRB Subsektor Pertanian', 'RPJMD_1_2', 'DISTAN', 'Definisi operasional Rasio PDRB Subsektor Pertanian menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: BPS (PDRB lapangan usaha)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F1","proposed_category_code":"RPJMD_1_2","rpjmd_level":"Sasaran","source_page":"III-19","source_data_proposal":"BPS (PDRB lapangan usaha)","supporting_organizations_proposal":"DKPP; Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinas Pertanian"}'::jsonb),
    ('RPJMD_I009_PERSENTASE_IRIGASI_KABUPATEN_DALAM_KONDISI_BAIK', 'Persentase irigasi kabupaten dalam kondisi baik', 'RPJMD_1_2', 'DPUPR', 'Definisi operasional Persentase irigasi kabupaten dalam kondisi baik menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: Dinas PUPR (data kondisi daerah irigasi)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F1","proposed_category_code":"RPJMD_1_2","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"Dinas PUPR (data kondisi daerah irigasi)","supporting_organizations_proposal":"Dinas Pertanian","assignment_basis":"Tabel 3.5 RPJMD","source_notes":"Juga relevan untuk Fokus 5 (infrastruktur); ditempatkan di Fokus 1 agar tidak ganda.","owner_label_from_matrix":"Dinas PUPR (Bidang SDA)"}'::jsonb),
    ('RPJMD_I010_RASIO_PDRB_SUBSEKTOR_PERIKANAN', 'Rasio PDRB Subsektor Perikanan', 'RPJMD_1_3', 'DKPP', 'Definisi operasional Rasio PDRB Subsektor Perikanan menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: BPS (PDRB lapangan usaha)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F1","proposed_category_code":"RPJMD_1_3","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"BPS (PDRB lapangan usaha)","supporting_organizations_proposal":"Disperindagkop-UKM; Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DKPP"}'::jsonb),
    ('RPJMD_I011_TINGKAT_INFLASI', 'Tingkat Inflasi', 'RPJMD_1_4', 'DISPERINDAGKOPUKM', 'Definisi operasional Tingkat Inflasi menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'decrease', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: BPS', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F1","proposed_category_code":"RPJMD_1_4","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"BPS","supporting_organizations_proposal":"Setda (Bagian Perekonomian/TPID); DKPP","assignment_basis":"Tabel 3.5 RPJMD","source_notes":"Target menurun (inflasi terkendali).","owner_label_from_matrix":"Disperindagkop-UKM"}'::jsonb),
    ('NILAI_INVESTASI', 'Jumlah nilai investasi berskala nasional (PMDN/PMA)', 'RPJMD_2_1', 'DPMPTSP', 'Definisi operasional Jumlah nilai investasi berskala nasional (PMDN/PMA) menunggu verifikasi OPD pemilik.', 'IDR', 'currency', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: Kementerian Investasi/BKPM (LKPM, OSS)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F2","proposed_category_code":"RPJMD_2_1","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"Kementerian Investasi/BKPM (LKPM, OSS)","supporting_organizations_proposal":"Disperindagkop-UKM; Setda (Bagian Perekonomian)","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DPMPTSP"}'::jsonb),
    ('KONTRIBUSI_INDUSTRI', 'Kontribusi PDRB Industri Pengolahan', 'RPJMD_2_2', 'DISPERINDAGKOPUKM', 'Definisi operasional Kontribusi PDRB Industri Pengolahan menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: BPS (PDRB lapangan usaha)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F2","proposed_category_code":"RPJMD_2_2","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"BPS (PDRB lapangan usaha)","supporting_organizations_proposal":"DPMPTSP; Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disperindagkop-UKM"}'::jsonb),
    ('PERTUMBUHAN_PDRB_KAPITA', 'Laju Pertumbuhan Ekonomi PDRB per Kapita', 'RPJMD_2_3', 'BAPPERIDA', 'Definisi operasional Laju Pertumbuhan Ekonomi PDRB per Kapita menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: BPS', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F2","proposed_category_code":"RPJMD_2_3","rpjmd_level":"Tujuan","source_page":"III-19","source_data_proposal":"BPS","supporting_organizations_proposal":"Setda (Bagian Perekonomian); seluruh OPD sektor ekonomi","assignment_basis":"Analisis (tusi OPD)","source_notes":null,"owner_label_from_matrix":"Bapperida"}'::jsonb),
    ('RPJMD_I015_PDRB_PER_KAPITA', 'PDRB per Kapita', 'RPJMD_2_3', 'BAPPERIDA', 'Definisi operasional PDRB per Kapita menunggu verifikasi OPD pemilik.', 'IDR_MILLION', 'currency', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: BPS', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F2","proposed_category_code":"RPJMD_2_3","rpjmd_level":"Tujuan","source_page":"III-19","source_data_proposal":"BPS","supporting_organizations_proposal":"Setda (Bagian Perekonomian); seluruh OPD sektor ekonomi","assignment_basis":"Analisis (tusi OPD)","source_notes":null,"owner_label_from_matrix":"Bapperida"}'::jsonb),
    ('RPJMD_I016_INDEKS_DAYA_SAING_DAERAH', 'Indeks Daya Saing Daerah', 'RPJMD_2_3', 'SETDA', 'Definisi operasional Indeks Daya Saing Daerah menunggu verifikasi OPD pemilik.', 'NUMBER', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: BRIN (IDSD)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F2","proposed_category_code":"RPJMD_2_3","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"BRIN (IDSD)","supporting_organizations_proposal":"Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Setda (Bagian Perekonomian dan SDA)"}'::jsonb),
    ('INDEKS_DESA', 'Indeks Desa', 'RPJMD_3_1', 'DPMD', 'Definisi operasional Indeks Desa menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: Kementerian Desa PDT (Indeks Desa)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F3","proposed_category_code":"RPJMD_3_1","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"Kementerian Desa PDT (Indeks Desa)","supporting_organizations_proposal":"Kecamatan; Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DPMD"}'::jsonb),
    ('DESA_MANDIRI', 'Persentase Desa Mandiri', 'RPJMD_3_1', 'DPMD', 'Definisi operasional Persentase Desa Mandiri menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: Kementerian Desa PDT (Indeks Desa)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F3","proposed_category_code":"RPJMD_3_1","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"Kementerian Desa PDT (Indeks Desa)","supporting_organizations_proposal":"Kecamatan; Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DPMD"}'::jsonb),
    ('RASIO_KEWIRAUSAHAAN', 'Rasio Kewirausahaan Daerah', 'RPJMD_3_2', 'DISPERINDAGKOPUKM', 'Definisi operasional Rasio Kewirausahaan Daerah menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: BPS (Sakernas) / data Disperindagkop-UKM', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F3","proposed_category_code":"RPJMD_3_2","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"BPS (Sakernas) / data Disperindagkop-UKM","supporting_organizations_proposal":"Disnakertrans; Disbudparpora (kepemudaan)","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disperindagkop-UKM"}'::jsonb),
    ('RPJMD_I021_RASIO_PDRB_SUBSEKTOR_PERDAGANGAN', 'Rasio PDRB Subsektor Perdagangan', 'RPJMD_3_2', 'DISPERINDAGKOPUKM', 'Definisi operasional Rasio PDRB Subsektor Perdagangan menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: BPS (PDRB lapangan usaha)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F3","proposed_category_code":"RPJMD_3_2","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"BPS (PDRB lapangan usaha)","supporting_organizations_proposal":"Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disperindagkop-UKM"}'::jsonb),
    ('RPJMD_I022_PAD_SEKTOR_PARIWISATA', 'PAD Sektor Pariwisata', 'RPJMD_3_3', NULL, 'Definisi operasional PAD Sektor Pariwisata menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: Bapenda/BKAD (realisasi PAD)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F3","proposed_category_code":"RPJMD_3_3","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"Bapenda/BKAD (realisasi PAD)","supporting_organizations_proposal":"Bapenda; BKAD","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disbudparpora"}'::jsonb),
    ('RPJMD_I023_RASIO_PDRB_PENYEDIAAN_AKOMODASI_DAN_MAKAN_MINUM', 'Rasio PDRB Penyediaan Akomodasi dan Makan Minum', 'RPJMD_3_3', NULL, 'Definisi operasional Rasio PDRB Penyediaan Akomodasi dan Makan Minum menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: BPS (PDRB lapangan usaha)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F3","proposed_category_code":"RPJMD_3_3","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"BPS (PDRB lapangan usaha)","supporting_organizations_proposal":"Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disbudparpora"}'::jsonb),
    ('RPJMD_I024_INDEKS_PEMBANGUNAN_MANUSIA_IPM', 'Indeks Pembangunan Manusia (IPM)', 'RPJMD_4_1', 'BAPPERIDA', 'Definisi operasional Indeks Pembangunan Manusia (IPM) menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: BPS', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_1","rpjmd_level":"Tujuan","source_page":"III-18","source_data_proposal":"BPS","supporting_organizations_proposal":"Dinkes; Disdik; Disperindagkop-UKM; Dinsos","assignment_basis":"Analisis (tusi OPD)","source_notes":null,"owner_label_from_matrix":"Bapperida"}'::jsonb),
    ('TINGKAT_KEMISKINAN', 'Tingkat Kemiskinan', 'RPJMD_4_1', 'DINSOS', 'Definisi operasional Tingkat Kemiskinan menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'decrease', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: BPS (Susenas)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_1","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"BPS (Susenas)","supporting_organizations_proposal":"Bapperida; DPMD; Disnakertrans","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinsos"}'::jsonb),
    ('RPJMD_I026_INDEKS_GINI', 'Indeks Gini', 'RPJMD_4_1', 'DINSOS', 'Definisi operasional Indeks Gini menunggu verifikasi OPD pemilik.', 'POINT', 'number', 'decrease', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: BPS (Susenas)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_1","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"BPS (Susenas)","supporting_organizations_proposal":"Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinsos"}'::jsonb),
    ('RPJMD_I027_TINGKAT_PENGANGGURAN_TERBUKA_TPT', 'Tingkat Pengangguran Terbuka (TPT)', 'RPJMD_4_1', 'DISNAKERTRANS', 'Definisi operasional Tingkat Pengangguran Terbuka (TPT) menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'decrease', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: BPS (Sakernas)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_1","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"BPS (Sakernas)","supporting_organizations_proposal":"Disperindagkop-UKM; Disdik","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disnakertrans"}'::jsonb),
    ('RPJMD_I028_TINGKAT_PARTISIPASI_ANGKATAN_KERJA_TPAK', 'Tingkat Partisipasi Angkatan Kerja (TPAK)', 'RPJMD_4_1', 'DISNAKERTRANS', 'Definisi operasional Tingkat Partisipasi Angkatan Kerja (TPAK) menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: BPS (Sakernas)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_1","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"BPS (Sakernas)","supporting_organizations_proposal":"Disperindagkop-UKM","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disnakertrans"}'::jsonb),
    ('RPJMD_I029_TPAK_PEREMPUAN', 'TPAK Perempuan', 'RPJMD_4_1', 'DISNAKERTRANS', 'Definisi operasional TPAK Perempuan menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: BPS (Sakernas)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_1","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"BPS (Sakernas)","supporting_organizations_proposal":"DP3APPKB","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disnakertrans"}'::jsonb),
    ('RPJMD_I030_USIA_HARAPAN_HIDUP_UHH', 'Usia Harapan Hidup (UHH)', 'RPJMD_4_2', 'DINKES', 'Definisi operasional Usia Harapan Hidup (UHH) menunggu verifikasi OPD pemilik.', 'YEAR', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: BPS', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_2","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"BPS","supporting_organizations_proposal":"Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinkes"}'::jsonb),
    ('RPJMD_I031_ANGKA_KEMATIAN_IBU_AKI', 'Angka Kematian Ibu (AKI)', 'RPJMD_4_2', 'DINKES', 'Definisi operasional Angka Kematian Ibu (AKI) menunggu verifikasi OPD pemilik.', 'PER_100K_LIVE_BIRTHS', 'number', 'decrease', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: Dinkes (laporan rutin kematian ibu)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_2","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"Dinkes (laporan rutin kematian ibu)","supporting_organizations_proposal":"DP3APPKB; RSUD","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinkes"}'::jsonb),
    ('PREVALENSI_STUNTING', 'Prevalensi Stunting (pendek dan sangat pendek)', 'RPJMD_4_2', 'DINKES', 'Definisi operasional Prevalensi Stunting (pendek dan sangat pendek) menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'decrease', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: Kemenkes (SSGI/SKI) / e-PPGBM', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_2","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"Kemenkes (SSGI/SKI) / e-PPGBM","supporting_organizations_proposal":"DP3APPKB; Bapperida (TPPS); DKPP; Dinas PUPR; Disperkimtan; DPMD","assignment_basis":"Tabel 3.5 RPJMD","source_notes":"Lintas fokus: dipengaruhi pula oleh air minum/sanitasi (5.2) dan pangan (1.1).","owner_label_from_matrix":"Dinkes"}'::jsonb),
    ('RPJMD_I033_CAKUPAN_KEPESERTAAN_JAMINAN_KESEHATAN_NASIONAL_JKN', 'Cakupan kepesertaan Jaminan Kesehatan Nasional (JKN)', 'RPJMD_4_2', 'DINKES', 'Definisi operasional Cakupan kepesertaan Jaminan Kesehatan Nasional (JKN) menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: BPJS Kesehatan', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_2","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"BPJS Kesehatan","supporting_organizations_proposal":"Dinsos (PBI); Disdukcapil","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinkes"}'::jsonb),
    ('RPJMD_I034_TREATMENT_COVERAGE_TUBERKULOSIS', 'Treatment Coverage Tuberkulosis', 'RPJMD_4_2', 'DINKES', 'Definisi operasional Treatment Coverage Tuberkulosis menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: Kemenkes (SITB)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_2","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"Kemenkes (SITB)","supporting_organizations_proposal":"RSUD; Puskesmas","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinkes"}'::jsonb),
    ('RPJMD_I035_ANGKA_KEBERHASILAN_PENGOBATAN_TBC_TREATMENT_SUCCESS_RATE', 'Angka keberhasilan pengobatan TBC (treatment success rate)', 'RPJMD_4_2', 'DINKES', 'Definisi operasional Angka keberhasilan pengobatan TBC (treatment success rate) menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: Kemenkes (SITB)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_2","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"Kemenkes (SITB)","supporting_organizations_proposal":"RSUD; Puskesmas","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinkes"}'::jsonb),
    ('RPJMD_I036_RATA_RATA_LAMA_SEKOLAH_RLS', 'Rata-rata Lama Sekolah (RLS)', 'RPJMD_4_3', 'DISDIK', 'Definisi operasional Rata-rata Lama Sekolah (RLS) menunggu verifikasi OPD pemilik.', 'YEAR', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: BPS', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_3","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"BPS","supporting_organizations_proposal":"Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disdik"}'::jsonb),
    ('RPJMD_I037_HARAPAN_LAMA_SEKOLAH_HLS', 'Harapan Lama Sekolah (HLS)', 'RPJMD_4_3', 'DISDIK', 'Definisi operasional Harapan Lama Sekolah (HLS) menunggu verifikasi OPD pemilik.', 'YEAR', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-18; usulan sumber data: BPS', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_3","rpjmd_level":"Sasaran","source_page":"III-18","source_data_proposal":"BPS","supporting_organizations_proposal":"Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disdik"}'::jsonb),
    ('LITERASI_DASAR', 'Kemampuan Literasi Pendidikan Dasar', 'RPJMD_4_3', 'DISDIK', 'Definisi operasional Kemampuan Literasi Pendidikan Dasar menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: Kemendikdasmen (Rapor Pendidikan/Asesmen Nasional)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_3","rpjmd_level":"Sasaran","source_page":"III-19","source_data_proposal":"Kemendikdasmen (Rapor Pendidikan/Asesmen Nasional)","supporting_organizations_proposal":"Disarpus","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disdik"}'::jsonb),
    ('RPJMD_I039_KEMAMPUAN_NUMERASI_PENDIDIKAN_DASAR', 'Kemampuan Numerasi Pendidikan Dasar', 'RPJMD_4_3', 'DISDIK', 'Definisi operasional Kemampuan Numerasi Pendidikan Dasar menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: Kemendikdasmen (Rapor Pendidikan/Asesmen Nasional)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_3","rpjmd_level":"Sasaran","source_page":"III-19","source_data_proposal":"Kemendikdasmen (Rapor Pendidikan/Asesmen Nasional)","supporting_organizations_proposal":"—","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disdik"}'::jsonb),
    ('RPJMD_I040_INDEKS_PEMBANGUNAN_LITERASI_MASYARAKAT', 'Indeks Pembangunan Literasi Masyarakat', 'RPJMD_4_3', 'DISARPUS', 'Definisi operasional Indeks Pembangunan Literasi Masyarakat menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: Perpustakaan Nasional (IPLM)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_3","rpjmd_level":"Sasaran","source_page":"III-19","source_data_proposal":"Perpustakaan Nasional (IPLM)","supporting_organizations_proposal":"Disdik","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disarpus"}'::jsonb),
    ('RPJMD_I041_INDEKS_PEMBANGUNAN_KUALITAS_KELUARGA', 'Indeks Pembangunan Kualitas Keluarga', 'RPJMD_4_4', 'DP3APPKB', 'Definisi operasional Indeks Pembangunan Kualitas Keluarga menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: Kemendukbangga/BKKBN (iBangga/IPKK)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_4","rpjmd_level":"Sasaran","source_page":"III-19","source_data_proposal":"Kemendukbangga/BKKBN (iBangga/IPKK)","supporting_organizations_proposal":"Dinsos; Dinkes","assignment_basis":"Tabel 3.5 RPJMD","source_notes":"Baseline 2025 tidak tersedia; target pertama 2026.","owner_label_from_matrix":"DP3APPKB"}'::jsonb),
    ('RPJMD_I042_INDEKS_KETIMPANGAN_GENDER_IKG', 'Indeks Ketimpangan Gender (IKG)', 'RPJMD_4_4', 'DP3APPKB', 'Definisi operasional Indeks Ketimpangan Gender (IKG) menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'decrease', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: BPS', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_4","rpjmd_level":"Sasaran","source_page":"III-19","source_data_proposal":"BPS","supporting_organizations_proposal":"Disnakertrans; Dinkes; Disdik","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DP3APPKB"}'::jsonb),
    ('RPJMD_I043_INDEKS_PERLINDUNGAN_ANAK_IPA', 'Indeks Perlindungan Anak (IPA)', 'RPJMD_4_4', 'DP3APPKB', 'Definisi operasional Indeks Perlindungan Anak (IPA) menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: KemenPPPA', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F4","proposed_category_code":"RPJMD_4_4","rpjmd_level":"Sasaran","source_page":"III-19","source_data_proposal":"KemenPPPA","supporting_organizations_proposal":"Dinsos; Disdik; Dinkes; Disdukcapil","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DP3APPKB"}'::jsonb),
    ('RPJMD_I044_INDEKS_KEPUASAN_LAYANAN_INFRASTRUKTUR', 'Indeks Kepuasan Layanan Infrastruktur', 'RPJMD_5_1', 'DPUPR', 'Definisi operasional Indeks Kepuasan Layanan Infrastruktur menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: Survei kepuasan daerah (metode perlu dipastikan)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F5","proposed_category_code":"RPJMD_5_1","rpjmd_level":"Tujuan","source_page":"III-20","source_data_proposal":"Survei kepuasan daerah (metode perlu dipastikan)","supporting_organizations_proposal":"Dishub; Disperkimtan; Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinas PUPR"}'::jsonb),
    ('INDEKS_KONEKTIVITAS', 'Indeks Konektivitas Wilayah', 'RPJMD_5_1', 'DISHUB', 'Definisi operasional Indeks Konektivitas Wilayah menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: Dishub/Bapperida (metode perlu dipastikan)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F5","proposed_category_code":"RPJMD_5_1","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"Dishub/Bapperida (metode perlu dipastikan)","supporting_organizations_proposal":"Dinas PUPR","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dishub"}'::jsonb),
    ('AKSES_AIR_MINUM', 'Persentase penduduk berakses air minum', 'RPJMD_5_2', 'DPUPR', 'Definisi operasional Persentase penduduk berakses air minum menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: BPS (Susenas) / Dinas PUPR', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F5","proposed_category_code":"RPJMD_5_2","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"BPS (Susenas) / Dinas PUPR","supporting_organizations_proposal":"Perumda Air Minum; Dinkes","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinas PUPR (Cipta Karya)"}'::jsonb),
    ('RUMAH_BERSANITASI', 'Persentase rumah tinggal bersanitasi', 'RPJMD_5_2', 'DPUPR', 'Definisi operasional Persentase rumah tinggal bersanitasi menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-20; usulan sumber data: BPS (Susenas) / Dinas PUPR', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F5","proposed_category_code":"RPJMD_5_2","rpjmd_level":"Sasaran","source_page":"III-20","source_data_proposal":"BPS (Susenas) / Dinas PUPR","supporting_organizations_proposal":"Disperkimtan; Dinkes (STBM); DLHK","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinas PUPR (Cipta Karya)"}'::jsonb),
    ('RPJMD_I048_PERSENTASE_DRAINASE_DALAM_KONDISI_BAIK', 'Persentase drainase dalam kondisi baik', 'RPJMD_5_2', 'DPUPR', 'Definisi operasional Persentase drainase dalam kondisi baik menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: Dinas PUPR', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F5","proposed_category_code":"RPJMD_5_2","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"Dinas PUPR","supporting_organizations_proposal":"Disperkimtan","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinas PUPR"}'::jsonb),
    ('RPJMD_I049_RUMAH_TANGGA_DENGAN_AKSES_HUNIAN_LAYAK_TERJANGKAU_DAN_BERK', 'Rumah tangga dengan akses hunian layak, terjangkau, dan berkelanjutan', 'RPJMD_5_3', 'DISPERKIMTAN', 'Definisi operasional Rumah tangga dengan akses hunian layak, terjangkau, dan berkelanjutan menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: BPS (Susenas) / Disperkimtan', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F5","proposed_category_code":"RPJMD_5_3","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"BPS (Susenas) / Disperkimtan","supporting_organizations_proposal":"Dinas PUPR; Dinsos","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disperkimtan"}'::jsonb),
    ('RPJMD_I050_INDEKS_KUALITAS_LINGKUNGAN_HIDUP_IKLH', 'Indeks Kualitas Lingkungan Hidup (IKLH)', 'RPJMD_6_1', 'DLHK', 'Definisi operasional Indeks Kualitas Lingkungan Hidup (IKLH) menunggu verifikasi OPD pemilik.', 'POINT', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: Kementerian LH/BPLH (rilis IKLH)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F6","proposed_category_code":"RPJMD_6_1","rpjmd_level":"Tujuan","source_page":"III-21","source_data_proposal":"Kementerian LH/BPLH (rilis IKLH)","supporting_organizations_proposal":"Dinas PUPR; Disperkimtan","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DLHK"}'::jsonb),
    ('RPJMD_I051_INDEKS_KUALITAS_AIR', 'Indeks Kualitas Air', 'RPJMD_6_1', 'DLHK', 'Definisi operasional Indeks Kualitas Air menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: Kementerian LH/BPLH; uji sampel DLHK', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F6","proposed_category_code":"RPJMD_6_1","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"Kementerian LH/BPLH; uji sampel DLHK","supporting_organizations_proposal":"Dinas PUPR (SDA)","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DLHK"}'::jsonb),
    ('RPJMD_I052_INDEKS_KUALITAS_UDARA', 'Indeks Kualitas Udara', 'RPJMD_6_1', 'DLHK', 'Definisi operasional Indeks Kualitas Udara menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: Kementerian LH/BPLH; uji sampel DLHK', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F6","proposed_category_code":"RPJMD_6_1","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"Kementerian LH/BPLH; uji sampel DLHK","supporting_organizations_proposal":"Dishub; Damkar","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DLHK"}'::jsonb),
    ('RPJMD_I053_INDEKS_TUTUPAN_LAHAN', 'Indeks Tutupan Lahan', 'RPJMD_6_1', 'DLHK', 'Definisi operasional Indeks Tutupan Lahan menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: Kementerian LH/BPLH; Kementerian Kehutanan', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F6","proposed_category_code":"RPJMD_6_1","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"Kementerian LH/BPLH; Kementerian Kehutanan","supporting_organizations_proposal":"Dinas Pertanian; Disperkimtan","assignment_basis":"Tabel 3.5 RPJMD","source_notes":"Target 2026 (78,50) lebih rendah dari 2025 (81,59) sesuai dokumen — perlu konfirmasi.","owner_label_from_matrix":"DLHK"}'::jsonb),
    ('RPJMD_I054_PERSENTASE_PENANGANAN_PERSAMPAHAN', 'Persentase Penanganan Persampahan', 'RPJMD_6_1', 'DLHK', 'Definisi operasional Persentase Penanganan Persampahan menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: DLHK (SIPSN)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F6","proposed_category_code":"RPJMD_6_1","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"DLHK (SIPSN)","supporting_organizations_proposal":"Disperkimtan; DPMD; Kecamatan","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DLHK"}'::jsonb),
    ('RPJMD_I055_PERSENTASE_PENURUNAN_EMISI_GRK', 'Persentase Penurunan Emisi GRK', 'RPJMD_6_2', 'DLHK', 'Definisi operasional Persentase Penurunan Emisi GRK menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: DLHK (inventarisasi GRK / SIGN-SMART)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F6","proposed_category_code":"RPJMD_6_2","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"DLHK (inventarisasi GRK / SIGN-SMART)","supporting_organizations_proposal":"Dinas Pertanian; Dishub; Dinas PUPR","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DLHK"}'::jsonb),
    ('RPJMD_I056_INDEKS_EKONOMI_HIJAU_DAERAH', 'Indeks Ekonomi Hijau Daerah', 'RPJMD_6_2', 'BAPPERIDA', 'Definisi operasional Indeks Ekonomi Hijau Daerah menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: Bapperida (metodologi Bappenas)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F6","proposed_category_code":"RPJMD_6_2","rpjmd_level":"Tujuan","source_page":"III-19","source_data_proposal":"Bapperida (metodologi Bappenas)","supporting_organizations_proposal":"DLHK; Disperindagkop-UKM; Dinas Pertanian","assignment_basis":"Analisis (tusi OPD)","source_notes":"Di RPJMD merupakan indikator Tujuan 3 (Misi 2); dikelompokkan ke Fokus 6 karena substansi ekonomi hijau.","owner_label_from_matrix":"Bapperida"}'::jsonb),
    ('RPJMD_I057_INDEKS_PENGELOLAAN_KEANEKARAGAMAN_HAYATI', 'Indeks Pengelolaan Keanekaragaman Hayati', 'RPJMD_6_2', 'DLHK', 'Definisi operasional Indeks Pengelolaan Keanekaragaman Hayati menunggu verifikasi OPD pemilik.', 'POINT', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: DLHK', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F6","proposed_category_code":"RPJMD_6_2","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"DLHK","supporting_organizations_proposal":"Dinas Pertanian; DKPP; Disperkimtan (tanah ulayat)","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"DLHK"}'::jsonb),
    ('RPJMD_I058_INDEKS_RISIKO_BENCANA', 'Indeks Risiko Bencana', 'RPJMD_6_3', 'BPBD', 'Definisi operasional Indeks Risiko Bencana menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'decrease', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: BNPB (IRBI)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F6","proposed_category_code":"RPJMD_6_3","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"BNPB (IRBI)","supporting_organizations_proposal":"Damkar; Dinsos; Dinas PUPR","assignment_basis":"Tabel 3.5 RPJMD","source_notes":"Nilai turun = membaik.","owner_label_from_matrix":"BPBD"}'::jsonb),
    ('RPJMD_I059_PERSENTASE_KETAATAN_PEMANFAATAN_RUANG_TERHADAP_RTRW', 'Persentase ketaatan pemanfaatan ruang terhadap RTRW', 'RPJMD_6_4', 'DPUPR', 'Definisi operasional Persentase ketaatan pemanfaatan ruang terhadap RTRW menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: Dinas PUPR', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F6","proposed_category_code":"RPJMD_6_4","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"Dinas PUPR","supporting_organizations_proposal":"Disperkimtan; DPMPTSP (KKPR); Satpol PP","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Dinas PUPR (Penataan Ruang)"}'::jsonb),
    ('RPJMD_I060_INDEKS_KERUKUNAN_UMAT_BERAGAMA', 'Indeks Kerukunan Umat Beragama', 'RPJMD_7_1', 'BAKESBANGPOL', 'Definisi operasional Indeks Kerukunan Umat Beragama menunggu verifikasi OPD pemilik.', 'POINT', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: Kementerian Agama (IKUB)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F7","proposed_category_code":"RPJMD_7_1","rpjmd_level":"Sasaran","source_page":"III-19","source_data_proposal":"Kementerian Agama (IKUB)","supporting_organizations_proposal":"Setda (Bagian Kesra); Satpol PP; Kemenag Kab. (vertikal); FKUB","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Kesbangpol"}'::jsonb),
    ('RPJMD_I061_INDEKS_PEMBANGUNAN_KEBUDAYAAN_IPK', 'Indeks Pembangunan Kebudayaan (IPK)', 'RPJMD_7_2', NULL, 'Definisi operasional Indeks Pembangunan Kebudayaan (IPK) menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-19; usulan sumber data: Kementerian Kebudayaan (IPK)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F7","proposed_category_code":"RPJMD_7_2","rpjmd_level":"Sasaran","source_page":"III-19","source_data_proposal":"Kementerian Kebudayaan (IPK)","supporting_organizations_proposal":"Disdik; Disarpus","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disbudparpora"}'::jsonb),
    ('RPJMD_I063_INDEKS_REFORMASI_BIROKRASI', 'Indeks Reformasi Birokrasi', 'RPJMD_8_1', 'SETDA', 'Definisi operasional Indeks Reformasi Birokrasi menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: KemenPANRB', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_1","rpjmd_level":"Tujuan","source_page":"III-21","source_data_proposal":"KemenPANRB","supporting_organizations_proposal":"Bapperida; Inspektorat; BKPSDM; Diskominfosantik","assignment_basis":"Analisis (tusi OPD)","source_notes":null,"owner_label_from_matrix":"Setda (Bagian Organisasi)"}'::jsonb),
    ('RPJMD_I064_NILAI_SISTEM_AKUNTABILITAS_KINERJA_INSTANSI_PEMERINTAH_SAK', 'Nilai Sistem Akuntabilitas Kinerja Instansi Pemerintah (SAKIP)', 'RPJMD_8_1', 'SETDA', 'Definisi operasional Nilai Sistem Akuntabilitas Kinerja Instansi Pemerintah (SAKIP) menunggu verifikasi OPD pemilik.', 'SCORE', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-22; usulan sumber data: KemenPANRB', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_1","rpjmd_level":"Sasaran","source_page":"III-22","source_data_proposal":"KemenPANRB","supporting_organizations_proposal":"Bapperida; Inspektorat; seluruh OPD","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Setda (Bagian Organisasi)"}'::jsonb),
    ('RPJMD_I065_INDEKS_INTEGRITAS', 'Indeks Integritas', 'RPJMD_8_1', 'INSPEKTORAT', 'Definisi operasional Indeks Integritas menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-22; usulan sumber data: KPK (Survei Penilaian Integritas)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_1","rpjmd_level":"Sasaran","source_page":"III-22","source_data_proposal":"KPK (Survei Penilaian Integritas)","supporting_organizations_proposal":"Setda; BKPSDM; seluruh OPD","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Inspektorat"}'::jsonb),
    ('RPJMD_I066_INDEKS_HASIL_PENGAWASAN_KEARSIPAN', 'Indeks Hasil Pengawasan Kearsipan', 'RPJMD_8_1', 'DISARPUS', 'Definisi operasional Indeks Hasil Pengawasan Kearsipan menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-22; usulan sumber data: ANRI', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_1","rpjmd_level":"Sasaran","source_page":"III-22","source_data_proposal":"ANRI","supporting_organizations_proposal":"Setda; seluruh OPD","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Disarpus"}'::jsonb),
    ('RPJMD_I067_INDEKS_SISTEM_PEMERINTAHAN_BERBASIS_ELEKTRONIK_SPBE', 'Indeks Sistem Pemerintahan Berbasis Elektronik (SPBE)', 'RPJMD_8_2', 'DISKOMINFOSANTIK', 'Definisi operasional Indeks Sistem Pemerintahan Berbasis Elektronik (SPBE) menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: KemenPANRB (evaluasi SPBE)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_2","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"KemenPANRB (evaluasi SPBE)","supporting_organizations_proposal":"Setda (Bagian Organisasi); Bapperida; seluruh OPD","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Diskominfosantik"}'::jsonb),
    ('RPJMD_I068_INDEKS_PEMBANGUNAN_TEKNOLOGI_INFORMASI_DAN_KOMUNIKASI', 'Indeks Pembangunan Teknologi Informasi dan Komunikasi', 'RPJMD_8_2', 'DISKOMINFOSANTIK', 'Definisi operasional Indeks Pembangunan Teknologi Informasi dan Komunikasi menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: BPS', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_2","rpjmd_level":"Sasaran","source_page":"III-21","source_data_proposal":"BPS","supporting_organizations_proposal":"—","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Diskominfosantik"}'::jsonb),
    ('RPJMD_I069_INDEKS_LITERASI_DIGITAL', 'Indeks Literasi Digital', 'RPJMD_8_2', 'DISKOMINFOSANTIK', 'Definisi operasional Indeks Literasi Digital menunggu verifikasi OPD pemilik.', 'NUMBER', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-21; usulan sumber data: Kementerian Komdigi', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_2","rpjmd_level":"Tujuan","source_page":"III-21","source_data_proposal":"Kementerian Komdigi","supporting_organizations_proposal":"Disdik; Disarpus","assignment_basis":"Analisis (tusi OPD)","source_notes":"Di RPJMD merupakan indikator Tujuan 6 (Misi 4).","owner_label_from_matrix":"Diskominfosantik"}'::jsonb),
    ('RPJMD_I070_INDEKS_INOVASI_DAERAH', 'Indeks Inovasi Daerah', 'RPJMD_8_2', 'BAPPERIDA', 'Definisi operasional Indeks Inovasi Daerah menunggu verifikasi OPD pemilik.', 'NUMBER', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-22; usulan sumber data: Kemendagri (BSKDN)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_2","rpjmd_level":"Sasaran","source_page":"III-22","source_data_proposal":"Kemendagri (BSKDN)","supporting_organizations_proposal":"Seluruh OPD","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Bapperida"}'::jsonb),
    ('RPJMD_I071_INDEKS_PELAYANAN_PUBLIK', 'Indeks Pelayanan Publik', 'RPJMD_8_3', 'SETDA', 'Definisi operasional Indeks Pelayanan Publik menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-22; usulan sumber data: KemenPANRB (evaluasi pelayanan publik)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_3","rpjmd_level":"Sasaran","source_page":"III-22","source_data_proposal":"KemenPANRB (evaluasi pelayanan publik)","supporting_organizations_proposal":"Disdukcapil; DPMPTSP; Dinkes; seluruh OPD pelayanan","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Setda (Bagian Organisasi)"}'::jsonb),
    ('RPJMD_I072_INDEKS_PROFESIONALITAS_ASN', 'Indeks Profesionalitas ASN', 'RPJMD_8_3', 'BKPSDM', 'Definisi operasional Indeks Profesionalitas ASN menunggu verifikasi OPD pemilik.', 'INDEX', 'number', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-22; usulan sumber data: BKN', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_3","rpjmd_level":"Sasaran","source_page":"III-22","source_data_proposal":"BKN","supporting_organizations_proposal":"Setda; seluruh OPD","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"BKPSDM"}'::jsonb),
    ('RPJMD_I073_OPINI_BPK_ATAS_LAPORAN_KEUANGAN', 'Opini BPK atas Laporan Keuangan', 'RPJMD_8_4', 'BKAD', 'Definisi operasional Opini BPK atas Laporan Keuangan menunggu verifikasi OPD pemilik.', 'RATING', 'text', 'maintain', 'RPJMD Kabupaten Kapuas 2025-2029, III-22; usulan sumber data: BPK RI', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_4","rpjmd_level":"Sasaran","source_page":"III-22","source_data_proposal":"BPK RI","supporting_organizations_proposal":"Inspektorat; seluruh OPD","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"BKAD"}'::jsonb),
    ('RPJMD_I074_RASIO_PAJAK_DAERAH_TERHADAP_PDRB', 'Rasio Pajak Daerah terhadap PDRB', 'RPJMD_8_4', 'BAPENDA', 'Definisi operasional Rasio Pajak Daerah terhadap PDRB menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'increase', 'RPJMD Kabupaten Kapuas 2025-2029, III-22; usulan sumber data: Bapenda (realisasi pajak) dan BPS (PDRB)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_4","rpjmd_level":"Sasaran","source_page":"III-22","source_data_proposal":"Bapenda (realisasi pajak) dan BPS (PDRB)","supporting_organizations_proposal":"BKAD; Bapperida","assignment_basis":"Tabel 3.5 RPJMD","source_notes":null,"owner_label_from_matrix":"Bapenda"}'::jsonb),
    ('RPJMD_I075_PERSENTASE_PENINGKATAN_PAD', 'Persentase peningkatan PAD', 'RPJMD_8_4', 'BAPENDA', 'Definisi operasional Persentase peningkatan PAD menunggu verifikasi OPD pemilik.', 'PERCENT', 'percentage', 'maintain', 'RPJMD Kabupaten Kapuas 2025-2029, III-22; usulan sumber data: Bapenda/BKAD (realisasi PAD)', '{"proposal_origin":"Matriks Fokus Isu Indikator RPJMD Kapuas 2025-2029","review_stage":"bapperida_draft","proposed_focus_code":"RPJMD_F8","proposed_category_code":"RPJMD_8_4","rpjmd_level":"Sasaran","source_page":"III-22","source_data_proposal":"Bapenda/BKAD (realisasi PAD)","supporting_organizations_proposal":"BKAD; OPD penghasil retribusi","assignment_basis":"Tabel 3.5 RPJMD","source_notes":"Pola target tidak wajar (30,76 → 2,42 → … → 7,33); konfirmasi ke BKAD/Bapenda.","owner_label_from_matrix":"Bapenda"}'::jsonb)
;

INSERT INTO sababuka.indicators (code, name, category_id, owner_organization_id, is_active)
SELECT d.code, d.name, c.id, o.id, true
FROM rpmd_indicator_drafts d
JOIN sababuka.categories c ON c.code = d.category_code
LEFT JOIN sababuka.organizations o ON o.code = d.owner_code
ON CONFLICT (code) DO UPDATE SET name = EXCLUDED.name, category_id = EXCLUDED.category_id, owner_organization_id = EXCLUDED.owner_organization_id, is_active = true, archived_at = NULL;

INSERT INTO sababuka.indicator_versions (indicator_id, version_number, definition, formula, unit_id, frequency, data_type, dimension_schema, direction, source_reference, access_level, effective_from, status, change_notes)
SELECT i.id, 1, d.definition, NULL, u.id, 'annual', d.data_type, d.dimension_schema, d.direction, d.source_reference, 'internal', DATE '2025-01-01', 'draft',
       'Draf hasil inventarisasi RPJMD. Menunggu review strategis Bapperida dan verifikasi teknis OPD.'
FROM rpmd_indicator_drafts d
JOIN sababuka.indicators i ON i.code = d.code
JOIN sababuka.units u ON u.code = d.unit_code
ON CONFLICT (indicator_id, version_number) DO UPDATE SET definition = EXCLUDED.definition, formula = EXCLUDED.formula, unit_id = EXCLUDED.unit_id, frequency = EXCLUDED.frequency, data_type = EXCLUDED.data_type, dimension_schema = EXCLUDED.dimension_schema, direction = EXCLUDED.direction, source_reference = EXCLUDED.source_reference, access_level = EXCLUDED.access_level, effective_from = EXCLUDED.effective_from, status = 'draft', change_notes = EXCLUDED.change_notes, submitted_by = NULL, submitted_at = NULL, approved_by = NULL, approved_at = NULL, updated_at = now();

DELETE FROM sababuka.indicator_organizations io USING sababuka.indicator_versions iv, sababuka.indicators i, rpmd_indicator_drafts d WHERE io.indicator_version_id = iv.id AND iv.indicator_id = i.id AND i.code = d.code;
INSERT INTO sababuka.indicator_organizations (indicator_version_id, organization_id, responsibility, is_primary)
SELECT iv.id, o.id, 'primary_producer', true
FROM rpmd_indicator_drafts d
JOIN sababuka.indicators i ON i.code = d.code
JOIN sababuka.indicator_versions iv ON iv.indicator_id = i.id AND iv.version_number = 1
JOIN sababuka.organizations o ON o.code = d.owner_code
ON CONFLICT DO NOTHING;

CREATE TEMP TABLE rpmd_target_drafts (indicator_code text, period_code text, numeric_value numeric, text_value text) ON COMMIT DROP;
INSERT INTO rpmd_target_drafts VALUES
    ('IKP', '2025', 83.49, NULL),
    ('IKP', '2026', 84.32, NULL),
    ('IKP', '2027', 85.16, NULL),
    ('IKP', '2028', 86.02, NULL),
    ('IKP', '2029', 86.88, NULL),
    ('PPH_KETERSEDIAAN', '2025', 88.78, NULL),
    ('PPH_KETERSEDIAAN', '2026', 90.56, NULL),
    ('PPH_KETERSEDIAAN', '2027', 92.37, NULL),
    ('PPH_KETERSEDIAAN', '2028', 94.21, NULL),
    ('PPH_KETERSEDIAAN', '2029', 96.1, NULL),
    ('RPJMD_I007_SKOR_POLA_PANGAN_HARAPAN_PPH_KONSUMSI', '2025', 83.0, NULL),
    ('RPJMD_I007_SKOR_POLA_PANGAN_HARAPAN_PPH_KONSUMSI', '2026', 84.0, NULL),
    ('RPJMD_I007_SKOR_POLA_PANGAN_HARAPAN_PPH_KONSUMSI', '2027', 84.5, NULL),
    ('RPJMD_I007_SKOR_POLA_PANGAN_HARAPAN_PPH_KONSUMSI', '2028', 85.0, NULL),
    ('RPJMD_I007_SKOR_POLA_PANGAN_HARAPAN_PPH_KONSUMSI', '2029', 85.5, NULL),
    ('RASIO_PDRB_PERTANIAN', '2025', 24.69, NULL),
    ('RASIO_PDRB_PERTANIAN', '2026', 24.89, NULL),
    ('RASIO_PDRB_PERTANIAN', '2027', 25.09, NULL),
    ('RASIO_PDRB_PERTANIAN', '2028', 25.29, NULL),
    ('RASIO_PDRB_PERTANIAN', '2029', 25.49, NULL),
    ('RPJMD_I009_PERSENTASE_IRIGASI_KABUPATEN_DALAM_KONDISI_BAIK', '2025', 37.0, NULL),
    ('RPJMD_I009_PERSENTASE_IRIGASI_KABUPATEN_DALAM_KONDISI_BAIK', '2026', 40.0, NULL),
    ('RPJMD_I009_PERSENTASE_IRIGASI_KABUPATEN_DALAM_KONDISI_BAIK', '2027', 43.0, NULL),
    ('RPJMD_I009_PERSENTASE_IRIGASI_KABUPATEN_DALAM_KONDISI_BAIK', '2028', 46.0, NULL),
    ('RPJMD_I009_PERSENTASE_IRIGASI_KABUPATEN_DALAM_KONDISI_BAIK', '2029', 49.0, NULL),
    ('RPJMD_I010_RASIO_PDRB_SUBSEKTOR_PERIKANAN', '2025', 5.1, NULL),
    ('RPJMD_I010_RASIO_PDRB_SUBSEKTOR_PERIKANAN', '2026', 5.2, NULL),
    ('RPJMD_I010_RASIO_PDRB_SUBSEKTOR_PERIKANAN', '2027', 5.4, NULL),
    ('RPJMD_I010_RASIO_PDRB_SUBSEKTOR_PERIKANAN', '2028', 5.5, NULL),
    ('RPJMD_I010_RASIO_PDRB_SUBSEKTOR_PERIKANAN', '2029', 5.6, NULL),
    ('RPJMD_I011_TINGKAT_INFLASI', '2025', 1.07, NULL),
    ('RPJMD_I011_TINGKAT_INFLASI', '2026', 1.06, NULL),
    ('RPJMD_I011_TINGKAT_INFLASI', '2027', 1.05, NULL),
    ('RPJMD_I011_TINGKAT_INFLASI', '2028', 1.04, NULL),
    ('RPJMD_I011_TINGKAT_INFLASI', '2029', 1.03, NULL),
    ('NILAI_INVESTASI', '2025', 1608057928154.29, NULL),
    ('NILAI_INVESTASI', '2026', 1704541404843.55, NULL),
    ('NILAI_INVESTASI', '2027', 1806814889134.16, NULL),
    ('NILAI_INVESTASI', '2028', 1915223782482.21, NULL),
    ('NILAI_INVESTASI', '2029', 2030137209431.14, NULL),
    ('KONTRIBUSI_INDUSTRI', '2025', 14.57, NULL),
    ('KONTRIBUSI_INDUSTRI', '2026', 15.2, NULL),
    ('KONTRIBUSI_INDUSTRI', '2027', 15.82, NULL),
    ('KONTRIBUSI_INDUSTRI', '2028', 16.45, NULL),
    ('KONTRIBUSI_INDUSTRI', '2029', 17.14, NULL),
    ('PERTUMBUHAN_PDRB_KAPITA', '2025', 5.2, NULL),
    ('PERTUMBUHAN_PDRB_KAPITA', '2026', 5.5, NULL),
    ('PERTUMBUHAN_PDRB_KAPITA', '2027', 5.7, NULL),
    ('PERTUMBUHAN_PDRB_KAPITA', '2028', 5.8, NULL),
    ('PERTUMBUHAN_PDRB_KAPITA', '2029', 6.0, NULL),
    ('RPJMD_I015_PDRB_PER_KAPITA', '2025', 60.671, NULL),
    ('RPJMD_I015_PDRB_PER_KAPITA', '2026', 62.909, NULL),
    ('RPJMD_I015_PDRB_PER_KAPITA', '2027', 65.235, NULL),
    ('RPJMD_I015_PDRB_PER_KAPITA', '2028', 67.655, NULL),
    ('RPJMD_I015_PDRB_PER_KAPITA', '2029', 70.172, NULL),
    ('RPJMD_I016_INDEKS_DAYA_SAING_DAERAH', '2025', 3.0, NULL),
    ('RPJMD_I016_INDEKS_DAYA_SAING_DAERAH', '2026', 3.06, NULL),
    ('RPJMD_I016_INDEKS_DAYA_SAING_DAERAH', '2027', 3.13, NULL),
    ('RPJMD_I016_INDEKS_DAYA_SAING_DAERAH', '2028', 3.19, NULL),
    ('RPJMD_I016_INDEKS_DAYA_SAING_DAERAH', '2029', 3.25, NULL),
    ('INDEKS_DESA', '2025', 0.7048, NULL),
    ('INDEKS_DESA', '2026', 0.7255, NULL),
    ('INDEKS_DESA', '2027', 0.7462, NULL),
    ('INDEKS_DESA', '2028', 0.7669, NULL),
    ('INDEKS_DESA', '2029', 0.7876, NULL),
    ('DESA_MANDIRI', '2025', 12.15, NULL),
    ('DESA_MANDIRI', '2026', 12.62, NULL),
    ('DESA_MANDIRI', '2027', 13.08, NULL),
    ('DESA_MANDIRI', '2028', 13.55, NULL),
    ('DESA_MANDIRI', '2029', 14.02, NULL),
    ('RASIO_KEWIRAUSAHAAN', '2025', 4.5, NULL),
    ('RASIO_KEWIRAUSAHAAN', '2026', 4.63, NULL),
    ('RASIO_KEWIRAUSAHAAN', '2027', 4.75, NULL),
    ('RASIO_KEWIRAUSAHAAN', '2028', 4.88, NULL),
    ('RASIO_KEWIRAUSAHAAN', '2029', 5.0, NULL),
    ('RPJMD_I021_RASIO_PDRB_SUBSEKTOR_PERDAGANGAN', '2025', 7.61, NULL),
    ('RPJMD_I021_RASIO_PDRB_SUBSEKTOR_PERDAGANGAN', '2026', 7.72, NULL),
    ('RPJMD_I021_RASIO_PDRB_SUBSEKTOR_PERDAGANGAN', '2027', 7.8, NULL),
    ('RPJMD_I021_RASIO_PDRB_SUBSEKTOR_PERDAGANGAN', '2028', 7.91, NULL),
    ('RPJMD_I021_RASIO_PDRB_SUBSEKTOR_PERDAGANGAN', '2029', 7.99, NULL),
    ('RPJMD_I022_PAD_SEKTOR_PARIWISATA', '2025', 5.0, NULL),
    ('RPJMD_I022_PAD_SEKTOR_PARIWISATA', '2026', 5.0, NULL),
    ('RPJMD_I022_PAD_SEKTOR_PARIWISATA', '2027', 5.0, NULL),
    ('RPJMD_I022_PAD_SEKTOR_PARIWISATA', '2028', 6.0, NULL),
    ('RPJMD_I022_PAD_SEKTOR_PARIWISATA', '2029', 6.0, NULL),
    ('RPJMD_I023_RASIO_PDRB_PENYEDIAAN_AKOMODASI_DAN_MAKAN_MINUM', '2025', 1.5, NULL),
    ('RPJMD_I023_RASIO_PDRB_PENYEDIAAN_AKOMODASI_DAN_MAKAN_MINUM', '2026', 1.56, NULL),
    ('RPJMD_I023_RASIO_PDRB_PENYEDIAAN_AKOMODASI_DAN_MAKAN_MINUM', '2027', 1.61, NULL),
    ('RPJMD_I023_RASIO_PDRB_PENYEDIAAN_AKOMODASI_DAN_MAKAN_MINUM', '2028', 1.67, NULL),
    ('RPJMD_I023_RASIO_PDRB_PENYEDIAAN_AKOMODASI_DAN_MAKAN_MINUM', '2029', 1.71, NULL),
    ('RPJMD_I024_INDEKS_PEMBANGUNAN_MANUSIA_IPM', '2025', 73.42, NULL),
    ('RPJMD_I024_INDEKS_PEMBANGUNAN_MANUSIA_IPM', '2026', 73.86, NULL),
    ('RPJMD_I024_INDEKS_PEMBANGUNAN_MANUSIA_IPM', '2027', 74.3, NULL),
    ('RPJMD_I024_INDEKS_PEMBANGUNAN_MANUSIA_IPM', '2028', 74.74, NULL),
    ('RPJMD_I024_INDEKS_PEMBANGUNAN_MANUSIA_IPM', '2029', 75.18, NULL),
    ('TINGKAT_KEMISKINAN', '2025', 5.0, NULL),
    ('TINGKAT_KEMISKINAN', '2026', 4.88, NULL),
    ('TINGKAT_KEMISKINAN', '2027', 4.76, NULL),
    ('TINGKAT_KEMISKINAN', '2028', 4.63, NULL),
    ('TINGKAT_KEMISKINAN', '2029', 4.5, NULL),
    ('RPJMD_I026_INDEKS_GINI', '2025', 0.307, NULL),
    ('RPJMD_I026_INDEKS_GINI', '2026', 0.306, NULL),
    ('RPJMD_I026_INDEKS_GINI', '2027', 0.303, NULL),
    ('RPJMD_I026_INDEKS_GINI', '2028', 0.301, NULL),
    ('RPJMD_I026_INDEKS_GINI', '2029', 0.299, NULL),
    ('RPJMD_I027_TINGKAT_PENGANGGURAN_TERBUKA_TPT', '2025', 3.5, NULL),
    ('RPJMD_I027_TINGKAT_PENGANGGURAN_TERBUKA_TPT', '2026', 3.47, NULL),
    ('RPJMD_I027_TINGKAT_PENGANGGURAN_TERBUKA_TPT', '2027', 3.45, NULL),
    ('RPJMD_I027_TINGKAT_PENGANGGURAN_TERBUKA_TPT', '2028', 3.42, NULL),
    ('RPJMD_I027_TINGKAT_PENGANGGURAN_TERBUKA_TPT', '2029', 3.4, NULL),
    ('RPJMD_I028_TINGKAT_PARTISIPASI_ANGKATAN_KERJA_TPAK', '2025', 72.0, NULL),
    ('RPJMD_I028_TINGKAT_PARTISIPASI_ANGKATAN_KERJA_TPAK', '2026', 72.5, NULL),
    ('RPJMD_I028_TINGKAT_PARTISIPASI_ANGKATAN_KERJA_TPAK', '2027', 73.0, NULL),
    ('RPJMD_I028_TINGKAT_PARTISIPASI_ANGKATAN_KERJA_TPAK', '2028', 73.5, NULL),
    ('RPJMD_I028_TINGKAT_PARTISIPASI_ANGKATAN_KERJA_TPAK', '2029', 74.0, NULL),
    ('RPJMD_I029_TPAK_PEREMPUAN', '2025', 49.45, NULL),
    ('RPJMD_I029_TPAK_PEREMPUAN', '2026', 49.45, NULL),
    ('RPJMD_I029_TPAK_PEREMPUAN', '2027', 49.46, NULL),
    ('RPJMD_I029_TPAK_PEREMPUAN', '2028', 49.46, NULL),
    ('RPJMD_I029_TPAK_PEREMPUAN', '2029', 49.47, NULL),
    ('RPJMD_I030_USIA_HARAPAN_HIDUP_UHH', '2025', 69.75, NULL),
    ('RPJMD_I030_USIA_HARAPAN_HIDUP_UHH', '2026', 69.87, NULL),
    ('RPJMD_I030_USIA_HARAPAN_HIDUP_UHH', '2027', 69.99, NULL),
    ('RPJMD_I030_USIA_HARAPAN_HIDUP_UHH', '2028', 70.11, NULL),
    ('RPJMD_I030_USIA_HARAPAN_HIDUP_UHH', '2029', 70.23, NULL),
    ('RPJMD_I031_ANGKA_KEMATIAN_IBU_AKI', '2025', 160.0, NULL),
    ('RPJMD_I031_ANGKA_KEMATIAN_IBU_AKI', '2026', 159.0, NULL),
    ('RPJMD_I031_ANGKA_KEMATIAN_IBU_AKI', '2027', 158.0, NULL),
    ('RPJMD_I031_ANGKA_KEMATIAN_IBU_AKI', '2028', 157.0, NULL),
    ('RPJMD_I031_ANGKA_KEMATIAN_IBU_AKI', '2029', 156.0, NULL),
    ('PREVALENSI_STUNTING', '2025', 19.2, NULL),
    ('PREVALENSI_STUNTING', '2026', 18.5, NULL),
    ('PREVALENSI_STUNTING', '2027', 17.6, NULL),
    ('PREVALENSI_STUNTING', '2028', 15.9, NULL),
    ('PREVALENSI_STUNTING', '2029', 14.2, NULL),
    ('RPJMD_I033_CAKUPAN_KEPESERTAAN_JAMINAN_KESEHATAN_NASIONAL_JKN', '2025', 90.0, NULL),
    ('RPJMD_I033_CAKUPAN_KEPESERTAAN_JAMINAN_KESEHATAN_NASIONAL_JKN', '2026', 90.62, NULL),
    ('RPJMD_I033_CAKUPAN_KEPESERTAAN_JAMINAN_KESEHATAN_NASIONAL_JKN', '2027', 91.24, NULL),
    ('RPJMD_I033_CAKUPAN_KEPESERTAAN_JAMINAN_KESEHATAN_NASIONAL_JKN', '2028', 91.86, NULL),
    ('RPJMD_I033_CAKUPAN_KEPESERTAAN_JAMINAN_KESEHATAN_NASIONAL_JKN', '2029', 92.5, NULL),
    ('RPJMD_I034_TREATMENT_COVERAGE_TUBERKULOSIS', '2025', 85.0, NULL),
    ('RPJMD_I034_TREATMENT_COVERAGE_TUBERKULOSIS', '2026', 85.0, NULL),
    ('RPJMD_I034_TREATMENT_COVERAGE_TUBERKULOSIS', '2027', 85.0, NULL),
    ('RPJMD_I034_TREATMENT_COVERAGE_TUBERKULOSIS', '2028', 85.0, NULL),
    ('RPJMD_I034_TREATMENT_COVERAGE_TUBERKULOSIS', '2029', 85.0, NULL),
    ('RPJMD_I035_ANGKA_KEBERHASILAN_PENGOBATAN_TBC_TREATMENT_SUCCESS_RATE', '2025', 90.0, NULL),
    ('RPJMD_I035_ANGKA_KEBERHASILAN_PENGOBATAN_TBC_TREATMENT_SUCCESS_RATE', '2026', 90.0, NULL),
    ('RPJMD_I035_ANGKA_KEBERHASILAN_PENGOBATAN_TBC_TREATMENT_SUCCESS_RATE', '2027', 90.0, NULL),
    ('RPJMD_I035_ANGKA_KEBERHASILAN_PENGOBATAN_TBC_TREATMENT_SUCCESS_RATE', '2028', 90.0, NULL),
    ('RPJMD_I035_ANGKA_KEBERHASILAN_PENGOBATAN_TBC_TREATMENT_SUCCESS_RATE', '2029', 90.0, NULL),
    ('RPJMD_I036_RATA_RATA_LAMA_SEKOLAH_RLS', '2025', 8.0, NULL),
    ('RPJMD_I036_RATA_RATA_LAMA_SEKOLAH_RLS', '2026', 8.18, NULL),
    ('RPJMD_I036_RATA_RATA_LAMA_SEKOLAH_RLS', '2027', 8.36, NULL),
    ('RPJMD_I036_RATA_RATA_LAMA_SEKOLAH_RLS', '2028', 8.54, NULL),
    ('RPJMD_I036_RATA_RATA_LAMA_SEKOLAH_RLS', '2029', 8.7, NULL),
    ('RPJMD_I037_HARAPAN_LAMA_SEKOLAH_HLS', '2025', 13.02, NULL),
    ('RPJMD_I037_HARAPAN_LAMA_SEKOLAH_HLS', '2026', 13.02, NULL),
    ('RPJMD_I037_HARAPAN_LAMA_SEKOLAH_HLS', '2027', 13.03, NULL),
    ('RPJMD_I037_HARAPAN_LAMA_SEKOLAH_HLS', '2028', 13.03, NULL),
    ('RPJMD_I037_HARAPAN_LAMA_SEKOLAH_HLS', '2029', 13.04, NULL),
    ('LITERASI_DASAR', '2025', 59.97, NULL),
    ('LITERASI_DASAR', '2026', 61.77, NULL),
    ('LITERASI_DASAR', '2027', 63.57, NULL),
    ('LITERASI_DASAR', '2028', 65.37, NULL),
    ('LITERASI_DASAR', '2029', 67.17, NULL),
    ('RPJMD_I039_KEMAMPUAN_NUMERASI_PENDIDIKAN_DASAR', '2025', 55.55, NULL),
    ('RPJMD_I039_KEMAMPUAN_NUMERASI_PENDIDIKAN_DASAR', '2026', 57.75, NULL),
    ('RPJMD_I039_KEMAMPUAN_NUMERASI_PENDIDIKAN_DASAR', '2027', 59.95, NULL),
    ('RPJMD_I039_KEMAMPUAN_NUMERASI_PENDIDIKAN_DASAR', '2028', 62.15, NULL),
    ('RPJMD_I039_KEMAMPUAN_NUMERASI_PENDIDIKAN_DASAR', '2029', 64.35, NULL),
    ('RPJMD_I040_INDEKS_PEMBANGUNAN_LITERASI_MASYARAKAT', '2025', 57.5, NULL),
    ('RPJMD_I040_INDEKS_PEMBANGUNAN_LITERASI_MASYARAKAT', '2026', 57.55, NULL),
    ('RPJMD_I040_INDEKS_PEMBANGUNAN_LITERASI_MASYARAKAT', '2027', 57.6, NULL),
    ('RPJMD_I040_INDEKS_PEMBANGUNAN_LITERASI_MASYARAKAT', '2028', 57.65, NULL),
    ('RPJMD_I040_INDEKS_PEMBANGUNAN_LITERASI_MASYARAKAT', '2029', 57.7, NULL),
    ('RPJMD_I041_INDEKS_PEMBANGUNAN_KUALITAS_KELUARGA', '2026', 56.69, NULL),
    ('RPJMD_I041_INDEKS_PEMBANGUNAN_KUALITAS_KELUARGA', '2027', 59.93, NULL),
    ('RPJMD_I041_INDEKS_PEMBANGUNAN_KUALITAS_KELUARGA', '2028', 60.17, NULL),
    ('RPJMD_I041_INDEKS_PEMBANGUNAN_KUALITAS_KELUARGA', '2029', 60.41, NULL),
    ('RPJMD_I042_INDEKS_KETIMPANGAN_GENDER_IKG', '2025', 0.538, NULL),
    ('RPJMD_I042_INDEKS_KETIMPANGAN_GENDER_IKG', '2026', 0.518, NULL),
    ('RPJMD_I042_INDEKS_KETIMPANGAN_GENDER_IKG', '2027', 0.498, NULL),
    ('RPJMD_I042_INDEKS_KETIMPANGAN_GENDER_IKG', '2028', 0.478, NULL),
    ('RPJMD_I042_INDEKS_KETIMPANGAN_GENDER_IKG', '2029', 0.458, NULL),
    ('RPJMD_I043_INDEKS_PERLINDUNGAN_ANAK_IPA', '2025', 66.68, NULL),
    ('RPJMD_I043_INDEKS_PERLINDUNGAN_ANAK_IPA', '2026', 68.0, NULL),
    ('RPJMD_I043_INDEKS_PERLINDUNGAN_ANAK_IPA', '2027', 68.78, NULL),
    ('RPJMD_I043_INDEKS_PERLINDUNGAN_ANAK_IPA', '2028', 69.0, NULL),
    ('RPJMD_I043_INDEKS_PERLINDUNGAN_ANAK_IPA', '2029', 69.55, NULL),
    ('RPJMD_I044_INDEKS_KEPUASAN_LAYANAN_INFRASTRUKTUR', '2025', 64.15, NULL),
    ('RPJMD_I044_INDEKS_KEPUASAN_LAYANAN_INFRASTRUKTUR', '2026', 65.0, NULL),
    ('RPJMD_I044_INDEKS_KEPUASAN_LAYANAN_INFRASTRUKTUR', '2027', 66.0, NULL),
    ('RPJMD_I044_INDEKS_KEPUASAN_LAYANAN_INFRASTRUKTUR', '2028', 67.0, NULL),
    ('RPJMD_I044_INDEKS_KEPUASAN_LAYANAN_INFRASTRUKTUR', '2029', 68.0, NULL),
    ('INDEKS_KONEKTIVITAS', '2025', 65.0, NULL),
    ('INDEKS_KONEKTIVITAS', '2026', 66.0, NULL),
    ('INDEKS_KONEKTIVITAS', '2027', 67.0, NULL),
    ('INDEKS_KONEKTIVITAS', '2028', 68.0, NULL),
    ('INDEKS_KONEKTIVITAS', '2029', 69.0, NULL),
    ('AKSES_AIR_MINUM', '2025', 41.0, NULL),
    ('AKSES_AIR_MINUM', '2026', 44.0, NULL),
    ('AKSES_AIR_MINUM', '2027', 47.0, NULL),
    ('AKSES_AIR_MINUM', '2028', 50.0, NULL),
    ('AKSES_AIR_MINUM', '2029', 53.0, NULL),
    ('RUMAH_BERSANITASI', '2025', 67.9, NULL),
    ('RUMAH_BERSANITASI', '2026', 70.0, NULL),
    ('RUMAH_BERSANITASI', '2027', 72.0, NULL),
    ('RUMAH_BERSANITASI', '2028', 74.0, NULL),
    ('RUMAH_BERSANITASI', '2029', 76.0, NULL),
    ('RPJMD_I048_PERSENTASE_DRAINASE_DALAM_KONDISI_BAIK', '2025', 86.0, NULL),
    ('RPJMD_I048_PERSENTASE_DRAINASE_DALAM_KONDISI_BAIK', '2026', 89.0, NULL),
    ('RPJMD_I048_PERSENTASE_DRAINASE_DALAM_KONDISI_BAIK', '2027', 92.0, NULL),
    ('RPJMD_I048_PERSENTASE_DRAINASE_DALAM_KONDISI_BAIK', '2028', 95.0, NULL),
    ('RPJMD_I048_PERSENTASE_DRAINASE_DALAM_KONDISI_BAIK', '2029', 98.0, NULL),
    ('RPJMD_I049_RUMAH_TANGGA_DENGAN_AKSES_HUNIAN_LAYAK_TERJANGKAU_DAN_BERK', '2025', 93.48, NULL),
    ('RPJMD_I049_RUMAH_TANGGA_DENGAN_AKSES_HUNIAN_LAYAK_TERJANGKAU_DAN_BERK', '2026', 95.0, NULL),
    ('RPJMD_I049_RUMAH_TANGGA_DENGAN_AKSES_HUNIAN_LAYAK_TERJANGKAU_DAN_BERK', '2027', 97.0, NULL),
    ('RPJMD_I049_RUMAH_TANGGA_DENGAN_AKSES_HUNIAN_LAYAK_TERJANGKAU_DAN_BERK', '2028', 99.0, NULL),
    ('RPJMD_I049_RUMAH_TANGGA_DENGAN_AKSES_HUNIAN_LAYAK_TERJANGKAU_DAN_BERK', '2029', 100.0, NULL),
    ('RPJMD_I050_INDEKS_KUALITAS_LINGKUNGAN_HIDUP_IKLH', '2025', 72.55, NULL),
    ('RPJMD_I050_INDEKS_KUALITAS_LINGKUNGAN_HIDUP_IKLH', '2026', 72.77, NULL),
    ('RPJMD_I050_INDEKS_KUALITAS_LINGKUNGAN_HIDUP_IKLH', '2027', 72.98, NULL),
    ('RPJMD_I050_INDEKS_KUALITAS_LINGKUNGAN_HIDUP_IKLH', '2028', 73.19, NULL),
    ('RPJMD_I050_INDEKS_KUALITAS_LINGKUNGAN_HIDUP_IKLH', '2029', 73.4, NULL),
    ('RPJMD_I051_INDEKS_KUALITAS_AIR', '2025', 59.41, NULL),
    ('RPJMD_I051_INDEKS_KUALITAS_AIR', '2026', 59.61, NULL),
    ('RPJMD_I051_INDEKS_KUALITAS_AIR', '2027', 59.81, NULL),
    ('RPJMD_I051_INDEKS_KUALITAS_AIR', '2028', 60.01, NULL),
    ('RPJMD_I051_INDEKS_KUALITAS_AIR', '2029', 60.21, NULL),
    ('RPJMD_I052_INDEKS_KUALITAS_UDARA', '2025', 79.87, NULL),
    ('RPJMD_I052_INDEKS_KUALITAS_UDARA', '2026', 80.17, NULL),
    ('RPJMD_I052_INDEKS_KUALITAS_UDARA', '2027', 80.47, NULL),
    ('RPJMD_I052_INDEKS_KUALITAS_UDARA', '2028', 80.77, NULL),
    ('RPJMD_I052_INDEKS_KUALITAS_UDARA', '2029', 81.07, NULL),
    ('RPJMD_I053_INDEKS_TUTUPAN_LAHAN', '2025', 81.59, NULL),
    ('RPJMD_I053_INDEKS_TUTUPAN_LAHAN', '2026', 78.5, NULL),
    ('RPJMD_I053_INDEKS_TUTUPAN_LAHAN', '2027', 81.66, NULL),
    ('RPJMD_I053_INDEKS_TUTUPAN_LAHAN', '2028', 81.8, NULL),
    ('RPJMD_I053_INDEKS_TUTUPAN_LAHAN', '2029', 81.87, NULL),
    ('RPJMD_I054_PERSENTASE_PENANGANAN_PERSAMPAHAN', '2025', 65.0, NULL),
    ('RPJMD_I054_PERSENTASE_PENANGANAN_PERSAMPAHAN', '2026', 66.25, NULL),
    ('RPJMD_I054_PERSENTASE_PENANGANAN_PERSAMPAHAN', '2027', 67.5, NULL),
    ('RPJMD_I054_PERSENTASE_PENANGANAN_PERSAMPAHAN', '2028', 68.75, NULL),
    ('RPJMD_I054_PERSENTASE_PENANGANAN_PERSAMPAHAN', '2029', 70.0, NULL),
    ('RPJMD_I055_PERSENTASE_PENURUNAN_EMISI_GRK', '2025', 8.946, NULL),
    ('RPJMD_I055_PERSENTASE_PENURUNAN_EMISI_GRK', '2026', 17.892, NULL),
    ('RPJMD_I055_PERSENTASE_PENURUNAN_EMISI_GRK', '2027', 26.838, NULL),
    ('RPJMD_I055_PERSENTASE_PENURUNAN_EMISI_GRK', '2028', 35.784, NULL),
    ('RPJMD_I055_PERSENTASE_PENURUNAN_EMISI_GRK', '2029', 44.73, NULL),
    ('RPJMD_I056_INDEKS_EKONOMI_HIJAU_DAERAH', '2025', 78.88, NULL),
    ('RPJMD_I056_INDEKS_EKONOMI_HIJAU_DAERAH', '2026', 79.66, NULL),
    ('RPJMD_I056_INDEKS_EKONOMI_HIJAU_DAERAH', '2027', 80.44, NULL),
    ('RPJMD_I056_INDEKS_EKONOMI_HIJAU_DAERAH', '2028', 81.22, NULL),
    ('RPJMD_I056_INDEKS_EKONOMI_HIJAU_DAERAH', '2029', 82.0, NULL),
    ('RPJMD_I057_INDEKS_PENGELOLAAN_KEANEKARAGAMAN_HAYATI', '2025', 0.35, NULL),
    ('RPJMD_I057_INDEKS_PENGELOLAAN_KEANEKARAGAMAN_HAYATI', '2026', 0.375, NULL),
    ('RPJMD_I057_INDEKS_PENGELOLAAN_KEANEKARAGAMAN_HAYATI', '2027', 0.4, NULL),
    ('RPJMD_I057_INDEKS_PENGELOLAAN_KEANEKARAGAMAN_HAYATI', '2028', 0.425, NULL),
    ('RPJMD_I057_INDEKS_PENGELOLAAN_KEANEKARAGAMAN_HAYATI', '2029', 0.45, NULL),
    ('RPJMD_I058_INDEKS_RISIKO_BENCANA', '2025', 132.83, NULL),
    ('RPJMD_I058_INDEKS_RISIKO_BENCANA', '2026', 131.55, NULL),
    ('RPJMD_I058_INDEKS_RISIKO_BENCANA', '2027', 130.27, NULL),
    ('RPJMD_I058_INDEKS_RISIKO_BENCANA', '2028', 129.017, NULL),
    ('RPJMD_I058_INDEKS_RISIKO_BENCANA', '2029', 127.72, NULL),
    ('RPJMD_I059_PERSENTASE_KETAATAN_PEMANFAATAN_RUANG_TERHADAP_RTRW', '2025', 54.27, NULL),
    ('RPJMD_I059_PERSENTASE_KETAATAN_PEMANFAATAN_RUANG_TERHADAP_RTRW', '2026', 56.24, NULL),
    ('RPJMD_I059_PERSENTASE_KETAATAN_PEMANFAATAN_RUANG_TERHADAP_RTRW', '2027', 58.2, NULL),
    ('RPJMD_I059_PERSENTASE_KETAATAN_PEMANFAATAN_RUANG_TERHADAP_RTRW', '2028', 60.16, NULL),
    ('RPJMD_I059_PERSENTASE_KETAATAN_PEMANFAATAN_RUANG_TERHADAP_RTRW', '2029', 62.12, NULL),
    ('RPJMD_I060_INDEKS_KERUKUNAN_UMAT_BERAGAMA', '2025', 70.0, NULL),
    ('RPJMD_I060_INDEKS_KERUKUNAN_UMAT_BERAGAMA', '2026', 71.25, NULL),
    ('RPJMD_I060_INDEKS_KERUKUNAN_UMAT_BERAGAMA', '2027', 72.5, NULL),
    ('RPJMD_I060_INDEKS_KERUKUNAN_UMAT_BERAGAMA', '2028', 73.25, NULL),
    ('RPJMD_I060_INDEKS_KERUKUNAN_UMAT_BERAGAMA', '2029', 75.0, NULL),
    ('RPJMD_I061_INDEKS_PEMBANGUNAN_KEBUDAYAAN_IPK', '2025', 50.0, NULL),
    ('RPJMD_I061_INDEKS_PEMBANGUNAN_KEBUDAYAAN_IPK', '2026', 51.25, NULL),
    ('RPJMD_I061_INDEKS_PEMBANGUNAN_KEBUDAYAAN_IPK', '2027', 52.5, NULL),
    ('RPJMD_I061_INDEKS_PEMBANGUNAN_KEBUDAYAAN_IPK', '2028', 53.75, NULL),
    ('RPJMD_I061_INDEKS_PEMBANGUNAN_KEBUDAYAAN_IPK', '2029', 55.0, NULL),
    ('RPJMD_I063_INDEKS_REFORMASI_BIROKRASI', '2025', 65.0, NULL),
    ('RPJMD_I063_INDEKS_REFORMASI_BIROKRASI', '2026', 65.6, NULL),
    ('RPJMD_I063_INDEKS_REFORMASI_BIROKRASI', '2027', 66.2, NULL),
    ('RPJMD_I063_INDEKS_REFORMASI_BIROKRASI', '2028', 66.8, NULL),
    ('RPJMD_I063_INDEKS_REFORMASI_BIROKRASI', '2029', 67.4, NULL),
    ('RPJMD_I064_NILAI_SISTEM_AKUNTABILITAS_KINERJA_INSTANSI_PEMERINTAH_SAK', '2025', 71.51, NULL),
    ('RPJMD_I064_NILAI_SISTEM_AKUNTABILITAS_KINERJA_INSTANSI_PEMERINTAH_SAK', '2026', 73.2, NULL),
    ('RPJMD_I064_NILAI_SISTEM_AKUNTABILITAS_KINERJA_INSTANSI_PEMERINTAH_SAK', '2027', 74.89, NULL),
    ('RPJMD_I064_NILAI_SISTEM_AKUNTABILITAS_KINERJA_INSTANSI_PEMERINTAH_SAK', '2028', 76.58, NULL),
    ('RPJMD_I064_NILAI_SISTEM_AKUNTABILITAS_KINERJA_INSTANSI_PEMERINTAH_SAK', '2029', 78.27, NULL),
    ('RPJMD_I065_INDEKS_INTEGRITAS', '2025', 70.0, NULL),
    ('RPJMD_I065_INDEKS_INTEGRITAS', '2026', 71.0, NULL),
    ('RPJMD_I065_INDEKS_INTEGRITAS', '2027', 72.0, NULL),
    ('RPJMD_I065_INDEKS_INTEGRITAS', '2028', 73.0, NULL),
    ('RPJMD_I065_INDEKS_INTEGRITAS', '2029', 74.0, NULL),
    ('RPJMD_I066_INDEKS_HASIL_PENGAWASAN_KEARSIPAN', '2025', 71.95, NULL),
    ('RPJMD_I066_INDEKS_HASIL_PENGAWASAN_KEARSIPAN', '2026', 71.96, NULL),
    ('RPJMD_I066_INDEKS_HASIL_PENGAWASAN_KEARSIPAN', '2027', 71.97, NULL),
    ('RPJMD_I066_INDEKS_HASIL_PENGAWASAN_KEARSIPAN', '2028', 71.98, NULL),
    ('RPJMD_I066_INDEKS_HASIL_PENGAWASAN_KEARSIPAN', '2029', 71.99, NULL),
    ('RPJMD_I067_INDEKS_SISTEM_PEMERINTAHAN_BERBASIS_ELEKTRONIK_SPBE', '2025', 2.5, NULL),
    ('RPJMD_I067_INDEKS_SISTEM_PEMERINTAHAN_BERBASIS_ELEKTRONIK_SPBE', '2026', 2.56, NULL),
    ('RPJMD_I067_INDEKS_SISTEM_PEMERINTAHAN_BERBASIS_ELEKTRONIK_SPBE', '2027', 2.63, NULL),
    ('RPJMD_I067_INDEKS_SISTEM_PEMERINTAHAN_BERBASIS_ELEKTRONIK_SPBE', '2028', 2.69, NULL),
    ('RPJMD_I067_INDEKS_SISTEM_PEMERINTAHAN_BERBASIS_ELEKTRONIK_SPBE', '2029', 2.75, NULL),
    ('RPJMD_I068_INDEKS_PEMBANGUNAN_TEKNOLOGI_INFORMASI_DAN_KOMUNIKASI', '2025', 5.5, NULL),
    ('RPJMD_I068_INDEKS_PEMBANGUNAN_TEKNOLOGI_INFORMASI_DAN_KOMUNIKASI', '2026', 5.575, NULL),
    ('RPJMD_I068_INDEKS_PEMBANGUNAN_TEKNOLOGI_INFORMASI_DAN_KOMUNIKASI', '2027', 5.65, NULL),
    ('RPJMD_I068_INDEKS_PEMBANGUNAN_TEKNOLOGI_INFORMASI_DAN_KOMUNIKASI', '2028', 5.725, NULL),
    ('RPJMD_I068_INDEKS_PEMBANGUNAN_TEKNOLOGI_INFORMASI_DAN_KOMUNIKASI', '2029', 5.8, NULL),
    ('RPJMD_I069_INDEKS_LITERASI_DIGITAL', '2025', 3.5, NULL),
    ('RPJMD_I069_INDEKS_LITERASI_DIGITAL', '2026', 3.55, NULL),
    ('RPJMD_I069_INDEKS_LITERASI_DIGITAL', '2027', 3.6, NULL),
    ('RPJMD_I069_INDEKS_LITERASI_DIGITAL', '2028', 3.65, NULL),
    ('RPJMD_I069_INDEKS_LITERASI_DIGITAL', '2029', 3.7, NULL),
    ('RPJMD_I070_INDEKS_INOVASI_DAERAH', '2025', 17.3, NULL),
    ('RPJMD_I070_INDEKS_INOVASI_DAERAH', '2026', 21.63, NULL),
    ('RPJMD_I070_INDEKS_INOVASI_DAERAH', '2027', 27.03, NULL),
    ('RPJMD_I070_INDEKS_INOVASI_DAERAH', '2028', 33.79, NULL),
    ('RPJMD_I070_INDEKS_INOVASI_DAERAH', '2029', 42.24, NULL),
    ('RPJMD_I071_INDEKS_PELAYANAN_PUBLIK', '2025', 3.5, NULL),
    ('RPJMD_I071_INDEKS_PELAYANAN_PUBLIK', '2026', 3.75, NULL),
    ('RPJMD_I071_INDEKS_PELAYANAN_PUBLIK', '2027', 4.0, NULL),
    ('RPJMD_I071_INDEKS_PELAYANAN_PUBLIK', '2028', 4.25, NULL),
    ('RPJMD_I071_INDEKS_PELAYANAN_PUBLIK', '2029', 4.5, NULL),
    ('RPJMD_I072_INDEKS_PROFESIONALITAS_ASN', '2025', 76.0, NULL),
    ('RPJMD_I072_INDEKS_PROFESIONALITAS_ASN', '2026', 77.0, NULL),
    ('RPJMD_I072_INDEKS_PROFESIONALITAS_ASN', '2027', 78.0, NULL),
    ('RPJMD_I072_INDEKS_PROFESIONALITAS_ASN', '2028', 79.0, NULL),
    ('RPJMD_I072_INDEKS_PROFESIONALITAS_ASN', '2029', 80.0, NULL),
    ('RPJMD_I073_OPINI_BPK_ATAS_LAPORAN_KEUANGAN', '2025', NULL, 'WTP'),
    ('RPJMD_I073_OPINI_BPK_ATAS_LAPORAN_KEUANGAN', '2026', NULL, 'WTP'),
    ('RPJMD_I073_OPINI_BPK_ATAS_LAPORAN_KEUANGAN', '2027', NULL, 'WTP'),
    ('RPJMD_I073_OPINI_BPK_ATAS_LAPORAN_KEUANGAN', '2028', NULL, 'WTP'),
    ('RPJMD_I073_OPINI_BPK_ATAS_LAPORAN_KEUANGAN', '2029', NULL, 'WTP'),
    ('RPJMD_I074_RASIO_PAJAK_DAERAH_TERHADAP_PDRB', '2025', 0.0019, NULL),
    ('RPJMD_I074_RASIO_PAJAK_DAERAH_TERHADAP_PDRB', '2026', 0.002, NULL),
    ('RPJMD_I074_RASIO_PAJAK_DAERAH_TERHADAP_PDRB', '2027', 0.002, NULL),
    ('RPJMD_I074_RASIO_PAJAK_DAERAH_TERHADAP_PDRB', '2028', 0.002, NULL),
    ('RPJMD_I074_RASIO_PAJAK_DAERAH_TERHADAP_PDRB', '2029', 0.0021, NULL),
    ('RPJMD_I075_PERSENTASE_PENINGKATAN_PAD', '2025', 30.76, NULL),
    ('RPJMD_I075_PERSENTASE_PENINGKATAN_PAD', '2026', 2.42, NULL),
    ('RPJMD_I075_PERSENTASE_PENINGKATAN_PAD', '2027', 2.8, NULL),
    ('RPJMD_I075_PERSENTASE_PENINGKATAN_PAD', '2028', 7.26, NULL),
    ('RPJMD_I075_PERSENTASE_PENINGKATAN_PAD', '2029', 7.33, NULL)
;
INSERT INTO sababuka.targets (indicator_version_id, period_id, numeric_value, text_value, notes)
SELECT iv.id, p.id, t.numeric_value, t.text_value, 'Target draf RPJMD; menunggu pengesahan Bapperida.'
FROM rpmd_target_drafts t
JOIN sababuka.indicators i ON i.code = t.indicator_code
JOIN sababuka.indicator_versions iv ON iv.indicator_id = i.id AND iv.version_number = 1
JOIN sababuka.periods p ON p.code = t.period_code
ON CONFLICT (indicator_version_id, period_id, geography_id, dimension_hash) DO UPDATE SET numeric_value = EXCLUDED.numeric_value, text_value = EXCLUDED.text_value, notes = EXCLUDED.notes, updated_at = now();

UPDATE sababuka.categories SET is_active = false, archived_at = COALESCE(archived_at, now()) WHERE code IN ('PANGAN_AGRO','INVESTASI_INDUSTRI','DESA_EKONOMI','SDM_SEJAHTERA','KONEKTIVITAS_LAYANAN');
UPDATE sababuka.policy_focuses SET is_active = false, archived_at = COALESCE(archived_at, now()) WHERE code = 'PILOT_ANTARA';

INSERT INTO sababuka.schema_migrations (version, description) VALUES ('015', 'RPJMD focus, issue group, indicator, owner, and target drafts for Bapperida review') ON CONFLICT (version) DO NOTHING;

COMMIT;
