import { Building2, CheckCircle2, ChevronRight, Clock3, CloudCog, Database, Download, FileCheck2, Link2, Plus, Search, Settings2, ShieldAlert, X } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { api, jsonBody } from "../api";
import { useAuth } from "../auth";
import { Badge, EmptyState, Modal, Notice, SortableHeader, Spinner, useAsync, type SortDirection } from "../components";
import type { Indicator, Organization, PageResponse } from "../types";

interface Candidate { type: "category" | "indicator"; code: string; name: string; source_title: string; score: number; reason: string; status: "mapped" | "unmapped" | "ambiguous" }
interface ConnectionProfile { source_code: string; reachable: boolean; response_ms: number | null; platform: string | null; dataset_count: number | null; resource_count: number | null; publishers: string[]; years: number[]; checked_at: string; error: string | null; candidate_summary: { candidate_count: number; mapped_count: number; unmapped_count: number; ambiguous_count: number; candidates: Candidate[]; annual_series_count?: number; structured_series_count?: number; series_candidates?: Array<{ title: string; dataset_name: string; years: number[]; formats: string[]; structured: boolean }> } }
interface SourceStatus { code: string; name: string; source_type: string; base_url: string; status: string; status_message?: string }
interface CkanResource { id: string; name: string; format?: string; url: string; datastore_active?: boolean }
interface CkanPackage { id: string; name: string; title: string; notes?: string; resources?: CkanResource[] }
interface Mapping { id: string; indicator_version_id: string; indicator_code: string; indicator_name: string; source_code: string; source_type: string; external_dataset_id: string; external_resource_id: string | null; resource_url: string | null; geography_code: string; year_field: string; value_field: string; status: string }
interface Run { id: string; status: string; preview_json: { rows_seen?: number; valid_rows?: number; invalid_rows?: number; years?: number[] }; values: Array<{ year: number; geography_code: string; numeric_value: string | null; text_value: string | null; validation_status: string; validation_errors: string[] }> }
interface IntegrationProfile { id: string; data_source_id: string; code: string; name: string; source_type: string; base_url: string | null; connection_config: { data_readiness_grade?: string; ckan_dataset_count?: number; rpjmd_indicator_count?: number; rpjmd_category_count?: number; pic_account_count?: number; website_url_confidence?: string; website_audit_status?: string }; organization_id: string; organization_name: string | null; connector_kind: IntegrationForm["connector_kind"]; auth_type: IntegrationForm["auth_type"]; data_format: IntegrationForm["data_format"]; endpoint_path: string | null; data_path: string | null; sync_mode: IntegrationForm["sync_mode"]; sync_interval_minutes: number | null; sync_timezone: string; verification_mode: IntegrationForm["verification_mode"]; status: "draft" | "testing" | "active" | "paused" | "error"; last_sync_status: string; last_synced_at: string | null; next_sync_at: string | null; notes: string | null; mapping_count: number; run_count: number }
interface WebsitePreview { status: "reachable" | "blocked" | "unreachable"; final_url: string | null; http_status: number | null; title: string | null; heading: string | null; years: number[]; table_count: number; document_links: Array<{ label: string; url: string; format: string }>; candidate_pages: Array<{ label: string; url: string }>; checked_at: string; message: string }
interface IntegrationForm { organization_id: string; code: string; name: string; connector_kind: "api_json" | "ckan" | "bps" | "csv_url" | "file_upload" | "database_view" | "html_scrape" | "manual"; base_url: string; endpoint_path: string; auth_type: "none" | "api_key" | "bearer" | "basic" | "oauth2"; data_format: "json" | "csv" | "xlsx" | "html" | "database" | "manual"; data_path: string; sync_mode: "manual" | "scheduled"; sync_interval_minutes: string; verification_mode: "preview_required" | "auto_import"; status: "draft" | "active" | "paused"; notes: string }

const sourceLabel = (status: string) => status === "connected" ? "Terhubung" : status === "waiting_api_key" ? "Menunggu API key" : status === "error" ? "Perlu diperiksa" : status;

export function ConnectorsPage() {
  const { user } = useAuth();
  const canManage = user?.permissions.includes("connector.manage") ?? false;
  const sources = useAsync(() => api<{ data: SourceStatus[] }>("/connectors/status"), []);
  const integrations = useAsync(() => api<{ data: IntegrationProfile[] }>("/connectors/integrations"), []);
  const organizations = useAsync(() => canManage ? api<PageResponse<Organization>>("/organizations?page_size=100&active=true") : Promise.resolve({ data: [], meta: { page: 1, page_size: 100, total_items: 0, total_pages: 0 } } as PageResponse<Organization>), [canManage]);
  const indicators = useAsync(() => canManage ? api<PageResponse<Indicator>>("/indicators?page=1&page_size=100&status=active") : Promise.resolve({ data: [], meta: { page: 1, page_size: 100, total_items: 0, total_pages: 0 } } as PageResponse<Indicator>), [canManage]);
  const mappings = useAsync(() => api<{ data: Mapping[] }>("/connectors/mappings"), []);
  const [query, setQuery] = useState(""); const [results, setResults] = useState<CkanPackage[]>([]); const [searchBusy, setSearchBusy] = useState(false); const [error, setError] = useState(""); const [run, setRun] = useState<Run | null>(null); const [profiles, setProfiles] = useState<Record<string, ConnectionProfile>>({}); const [profileBusy, setProfileBusy] = useState<string | null>(null);
  const [integrationOpen, setIntegrationOpen] = useState(false); const [editingIntegration, setEditingIntegration] = useState<IntegrationProfile | null>(null);
  const [integrationQuery, setIntegrationQuery] = useState(""); const [readinessFilter, setReadinessFilter] = useState("all");
  const [scrapeBusy, setScrapeBusy] = useState<string | null>(null); const [scrapePreviews, setScrapePreviews] = useState<Record<string, WebsitePreview>>({});
  const [mappingSortBy, setMappingSortBy] = useState("indicator_code"); const [mappingSortOrder, setMappingSortOrder] = useState<SortDirection>("asc");
  const [previewSortBy, setPreviewSortBy] = useState("year"); const [previewSortOrder, setPreviewSortOrder] = useState<SortDirection>("desc");
  const [form, setForm] = useState({ indicator_version_id: "", source_code: "SATUDATA_KAPUAS", external_dataset_id: "", external_resource_id: "", resource_url: "", geography_field: "", geography_code: "6203", year_field: "tahun", value_field: "nilai", unit_field: "", expected_unit: "" });
  useEffect(() => {
    const closeResults = (event: KeyboardEvent) => { if (event.key === "Escape") setResults([]); };
    window.addEventListener("keydown", closeResults);
    return () => window.removeEventListener("keydown", closeResults);
  }, []);
  const searchCkan = async () => { setSearchBusy(true); setError(""); try { const result = await api<{ results: CkanPackage[] }>(`/connectors/ckan/search?q=${encodeURIComponent(query)}&rows=10`); setResults(result.results); } catch (cause) { setError(cause instanceof Error ? cause.message : "Katalog tidak dapat dicari."); } finally { setSearchBusy(false); } };
  const saveMapping = async () => { setError(""); try { await api("/connectors/mappings", { method: "POST", mutation: true, body: jsonBody({ ...form, external_resource_id: form.external_resource_id || null, resource_url: form.resource_url || null, geography_field: form.geography_field || null, unit_field: form.unit_field || null, expected_unit: form.expected_unit || null }) }); mappings.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Mapping gagal disimpan."); } };
  const mappingAction = async (mapping: Mapping, action: "approve" | "activate" | "sync") => {
    setError("");
    try {
      if (action === "sync") {
        const syncResult = await api<Run>(`/connectors/mappings/${mapping.id}/sync`, { method: "POST", mutation: true });
        setRun(syncResult);
      } else {
        await api<Mapping>(`/connectors/mappings/${mapping.id}/actions/${action}`, { method: "POST", mutation: true });
      }
      mappings.reload();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Aksi konektor gagal.");
    }
  };
  const importRun = async () => { if (!run) return; setError(""); try { setRun(await api<Run>(`/connectors/runs/${run.id}/import`, { method: "POST", mutation: true })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Import gagal."); } };
  const testConnection = async (sourceCode: "SATUDATA_KAPUAS" | "BPS_KAPUAS") => { setProfileBusy(sourceCode); setError(""); try { const profile = await api<ConnectionProfile>(`/connectors/${sourceCode}/test`, { method: "POST", mutation: true }); setProfiles((current) => ({ ...current, [sourceCode]: profile })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Uji koneksi gagal."); } finally { setProfileBusy(null); } };
  const inspectWebsite = async (profile: IntegrationProfile) => { setScrapeBusy(profile.id); setError(""); try { const preview = await api<WebsitePreview>(`/connectors/integrations/${profile.id}/scrape-preview`, { method: "POST", mutation: true }); setScrapePreviews((current) => ({ ...current, [profile.id]: preview })); integrations.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Website belum dapat diperiksa."); } finally { setScrapeBusy(null); } };
  const filteredIntegrations = useMemo(() => (integrations.data?.data ?? []).filter((item) => {
    if (item.connector_kind !== "html_scrape") return false;
    const matchesQuery = `${item.organization_name ?? ""} ${item.name} ${item.code}`.toLocaleLowerCase("id").includes(integrationQuery.trim().toLocaleLowerCase("id"));
    const matchesReadiness = readinessFilter === "all" || item.connection_config?.data_readiness_grade === readinessFilter;
    return matchesQuery && matchesReadiness;
  }), [integrations.data?.data, integrationQuery, readinessFilter]);
  const sortedMappings = useMemo(() => [...(mappings.data?.data ?? [])].sort((a, b) => {
    const value = (item: Mapping) => mappingSortBy === "columns" ? `${item.year_field} ${item.value_field} ${item.geography_code}` : item[mappingSortBy as keyof Mapping] ?? "";
    const compared = String(value(a)).localeCompare(String(value(b)), "id", { numeric: true });
    return mappingSortOrder === "asc" ? compared : -compared;
  }), [mappings.data?.data, mappingSortBy, mappingSortOrder]);
  const sortedRunValues = useMemo(() => [...(run?.values ?? [])].sort((a, b) => {
    const value = (item: typeof a) => previewSortBy === "value" ? item.numeric_value ?? item.text_value ?? "" : item[previewSortBy as keyof typeof item] ?? "";
    const left = value(a); const right = value(b);
    const compared = typeof left === "number" && typeof right === "number" ? left - right : String(left).localeCompare(String(right), "id", { numeric: true });
    return previewSortOrder === "asc" ? compared : -compared;
  }), [run?.values, previewSortBy, previewSortOrder]);
  return <>
    {error && <Notice tone="error">{error}</Notice>}
    <section className="walidata-identity"><span><FileCheck2 /></span><div><small>Peran resmi</small><h2>Diskominfosantik sebagai Walidata Kabupaten Kapuas</h2><p>Walidata memastikan data lintas OPD memiliki metadata, struktur, sumber, dan aliran teknis yang dapat dipertanggungjawabkan. BAPPERIDA tetap memutuskan substansi indikator; OPD tetap bertanggung jawab atas isi data; Pengelola Sistem menjaga akun, keamanan, dan konfigurasi rahasia.</p></div></section>
    {!canManage && <Notice tone="warning">Mode pemantauan. Hubungi Pengelola Sistem jika kewenangan Walidata untuk mapping dan sinkronisasi belum diaktifkan pada akun ini.</Notice>}
    <section className="integration-flow" aria-label="Alur integrasi data OPD"><div><span><Building2 /></span><strong>1. Daftarkan sumber</strong><small>OPD, alamat, dan jenis sistem</small></div><ChevronRight /><div><span><Database /></span><strong>2. Petakan data</strong><small>Indikator, periode, nilai, wilayah</small></div><ChevronRight /><div><span><ShieldAlert /></span><strong>3. Periksa preview</strong><small>Validasi sebelum masuk</small></div><ChevronRight /><div><span><Clock3 /></span><strong>4. Sinkronkan</strong><small>Manual atau terjadwal</small></div></section>
    <section className="panel integration-registry">
      <header className="panel-heading"><div><span className="eyebrow">Direktori integrasi OPD</span><h2>Peta kesiapan sumber data OPD</h2><p>Website hanya diperiksa sebagai kandidat sumber. Data tidak langsung masuk ke indikator tanpa mapping dan persetujuan Walidata.</p></div>{canManage && <button className="button primary" onClick={() => { setEditingIntegration(null); setIntegrationOpen(true); }}><Plus />Daftarkan sumber OPD</button>}</header>
      {!integrations.loading && Boolean(integrations.data?.data.length) && <><div className="opd-source-summary"><div><small>Sumber terdaftar</small><strong>{integrations.data!.data.filter((item) => item.connector_kind === "html_scrape").length} OPD</strong></div><div><small>Siap dipetakan (A)</small><strong>{integrations.data!.data.filter((item) => item.connection_config?.data_readiness_grade === "A").length}</strong></div><div><small>Perlu dilengkapi (C–D)</small><strong>{integrations.data!.data.filter((item) => ["C", "D"].includes(item.connection_config?.data_readiness_grade ?? "")).length}</strong></div><div><small>Otomasi aktif</small><strong>0</strong></div></div><div className="toolbar integration-filter"><label className="search-field"><Search /><input aria-label="Cari OPD atau sumber" value={integrationQuery} onChange={(event) => setIntegrationQuery(event.target.value)} placeholder="Cari OPD atau nama sumber" /></label><label className="field compact-field"><span>Kesiapan data</span><select value={readinessFilter} onChange={(event) => setReadinessFilter(event.target.value)}><option value="all">Semua tingkat</option><option value="A">A — siap dipetakan</option><option value="B">B — sumber tersedia</option><option value="C">C — perlu dilengkapi</option><option value="D">D — belum siap</option></select></label></div></>}
      {integrations.loading ? <div className="panel-loading"><Spinner /></div> : !integrations.data?.data.length ? <EmptyState title="Belum ada sumber OPD">Daftarkan API, portal data, file berkala, atau sumber manual milik OPD.</EmptyState> : !filteredIntegrations.length ? <EmptyState title="Sumber tidak ditemukan">Ubah kata pencarian atau filter kesiapan.</EmptyState> : <div className="integration-card-grid">{filteredIntegrations.map((item) => { const preview = scrapePreviews[item.id]; const config = item.connection_config ?? {}; return <article className="integration-card" key={item.id}><header><span className="table-icon"><Database /></span><div><strong>{item.organization_name ?? item.name}</strong><small>{item.code}</small></div><Badge tone={config.data_readiness_grade === "A" ? "success" : config.data_readiness_grade === "D" ? "danger" : "warning"}>Kesiapan {config.data_readiness_grade ?? "-"}</Badge></header><dl><div><dt>Indikator RPJMD</dt><dd>{config.rpjmd_indicator_count ?? item.mapping_count}</dd></div><div><dt>Kategori terkait</dt><dd>{config.rpjmd_category_count ?? "-"}</dd></div><div><dt>Dataset Satu Data</dt><dd>{config.ckan_dataset_count ?? "-"}</dd></div><div><dt>PIC aktif</dt><dd>{config.pic_account_count ?? "-"}</dd></div></dl><p className="source-url">{item.base_url ?? "Alamat website belum tersedia"}</p>{config.website_url_confidence === "needs_confirmation" && <small className="source-warning">Alamat perlu dikonfirmasi OPD/Walidata.</small>}{preview && <div className={`scrape-preview ${preview.status}`}><strong>{preview.status === "reachable" ? "Halaman dapat dibaca" : preview.status === "blocked" ? "Akses otomatis ditolak" : "Belum terjangkau"}</strong><small>{preview.message}</small>{preview.status === "reachable" && <small>{preview.years.length ? `Tahun terdeteksi: ${preview.years.join(", ")}` : "Belum ada tahun terdeteksi"} · {preview.table_count} tabel · {preview.document_links.length} dokumen</small>}</div>}<footer><span><small>Pemeriksaan terakhir</small><strong>{item.last_synced_at ? new Date(item.last_synced_at).toLocaleString("id-ID") : "Belum diperiksa"}</strong></span><span className="table-actions">{canManage && item.connector_kind === "html_scrape" && <button className="button secondary compact" disabled={scrapeBusy === item.id} onClick={() => void inspectWebsite(item)}><Search />{scrapeBusy === item.id ? "Memeriksa…" : "Periksa website"}</button>}{canManage && <button className="button secondary compact" onClick={() => { setEditingIntegration(item); setIntegrationOpen(true); }}><Settings2 />Pengaturan</button>}</span></footer></article>; })}</div>}
    </section>
    <section className="summary-grid connector-summary-grid">{sources.loading ? <Spinner /> : sources.data?.data.map((source) => <article className="summary-card connector-source-card" key={source.code}><span className="table-icon"><CloudCog /></span><div><small>{source.name}</small><strong>{sourceLabel(source.status)}</strong><p>{source.status_message ?? source.base_url}</p>{canManage && <button className="button secondary compact" onClick={() => void testConnection(source.code as "SATUDATA_KAPUAS" | "BPS_KAPUAS")} disabled={profileBusy === source.code}>{profileBusy === source.code ? "Menguji…" : "Uji koneksi"}</button>}{profiles[source.code] && <ConnectionProfileCard profile={profiles[source.code]!} />}</div></article>)}</section>
    <Notice tone="warning">Konektor dapat membaca seri historis sebagai pembanding tren. Target RPJMD tetap mengikuti periode 2025–2029; Walidata memeriksa mapping, satuan, wilayah, dan hasil sinkronisasi sebelum data dipakai.</Notice>
    {canManage && <section className="mapping-guide" aria-label="Cara kerja mapping sumber"><div><strong>Cara kerja mapping</strong><p>Satu mapping mengikat satu resource sumber ke satu indikator aktif. Menyimpan mapping belum memindahkan data.</p></div><ol><li><b>1</b>Pilih dataset</li><li><b>2</b>Tentukan indikator dan kolom</li><li><b>3</b>Simpan serta periksa draf</li><li><b>4</b>Aktifkan, preview, lalu impor</li></ol></section>}
    {canManage && <section className="panel connector-panel"><header className="panel-heading"><div><span className="eyebrow">Pencarian katalog</span><h2>Cari dataset Satu Data Kapuas</h2><p>Hasil pencarian hanya menjadi kandidat. Data baru masuk setelah mapping disimpan dan disetujui.</p></div><Search /></header><div className="toolbar connector-toolbar"><input aria-label="Cari dataset" value={query} onChange={(event) => { setQuery(event.target.value); if (!event.target.value.trim()) setResults([]); }} placeholder="Contoh: kesehatan, IKP, stunting" /><button className="button secondary" onClick={() => void searchCkan()} disabled={searchBusy || !query.trim()}><Search />{searchBusy ? "Mencari…" : "Cari katalog"}</button></div>{results.length > 0 && <div className="catalog-results-panel"><header><span><strong>{results.length} dataset ditemukan</strong><small>Pilih satu dataset atau tutup hasil untuk kembali.</small></span><button className="icon-button" aria-label="Tutup hasil pencarian" title="Tutup hasil" onClick={() => setResults([])}><X /></button></header><div className="candidate-list connector-results">{results.map((item) => <article key={item.id}><span><strong>{item.title}</strong><small>{item.name} · {item.resources?.length ?? 0} resource</small></span><button className="button secondary compact" onClick={() => { const resource = item.resources?.find((candidate) => ["CSV", "JSON", "XLSX"].includes((candidate.format ?? "").toUpperCase()) || (candidate.url ?? "").toLowerCase().includes(".xlsx")); setForm((current) => ({ ...current, external_dataset_id: item.id, external_resource_id: resource?.id ?? "", resource_url: resource?.url ?? "" })); setResults([]); document.getElementById("mapping-form")?.scrollIntoView({ behavior: "smooth", block: "start" }); }}>Pilih untuk mapping</button></article>)}</div><small className="catalog-close-hint">Tekan Esc atau tombol tutup untuk menyembunyikan hasil.</small></div>}</section>}
    {canManage && indicators.data && <section className="panel connector-panel"><header className="panel-heading"><div><span className="eyebrow">Mapping eksplisit</span><h2>Hubungkan sumber ke indikator aktif</h2><p>Pilih sumber yang telah didaftarkan, lalu tunjukkan kolom periode, nilai, wilayah, dan satuannya.</p></div><Link2 /></header><div className="form-grid connector-form"><label className="field"><span>Indikator</span><select value={form.indicator_version_id} onChange={(event) => setForm({ ...form, indicator_version_id: event.target.value })}><option value="">Pilih indikator</option>{indicators.data.data.map((item) => <option key={item.version_id} value={item.version_id}>{item.code} - {item.name}</option>)}</select></label><label className="field"><span>Sumber terdaftar</span><select value={form.source_code} onChange={(event) => setForm({ ...form, source_code: event.target.value })}><option value="">Pilih sumber</option>{integrations.data?.data.map((item) => <option key={item.id} value={item.code}>{item.name} — {item.organization_name ?? "Lintas OPD"}</option>)}</select></label><label className="field"><span>Dataset/package ID</span><input value={form.external_dataset_id} onChange={(event) => setForm({ ...form, external_dataset_id: event.target.value })} /></label><label className="field"><span>Resource ID</span><input value={form.external_resource_id} onChange={(event) => setForm({ ...form, external_resource_id: event.target.value })} /></label><label className="field connector-wide"><span>URL resource</span><input value={form.resource_url} onChange={(event) => setForm({ ...form, resource_url: event.target.value })} /></label><label className="field"><span>Kolom tahun</span><input value={form.year_field} onChange={(event) => setForm({ ...form, year_field: event.target.value })} /></label><label className="field"><span>Kolom nilai</span><input value={form.value_field} onChange={(event) => setForm({ ...form, value_field: event.target.value })} /></label><label className="field"><span>Kolom wilayah</span><input value={form.geography_field} onChange={(event) => setForm({ ...form, geography_field: event.target.value })} placeholder="Kosong jika dataset khusus Kapuas" /></label><label className="field"><span>Kode wilayah</span><input value={form.geography_code} onChange={(event) => setForm({ ...form, geography_code: event.target.value })} /></label></div><div className="panel-actions"><button className="button primary" disabled={!form.indicator_version_id || !form.source_code || !form.external_dataset_id} onClick={() => void saveMapping()}><Link2 />Simpan sebagai draf</button></div></section>}
    <section className="panel table-panel connector-panel"><header className="panel-heading"><div><span className="eyebrow">Pekerjaan Walidata</span><h2>Mapping dan sinkronisasi sumber</h2><p>Pastikan sumber, kolom, wilayah, satuan, dan hasil preview sesuai sebelum data diimpor.</p></div><ShieldAlert /></header>{mappings.loading ? <div className="panel-loading"><Spinner /></div> : !mappings.data?.data.length ? <EmptyState title="Belum ada mapping sumber">Walidata dapat membuat mapping setelah indikator aktif tersedia. Jika master belum aktif, tunggu keputusan BAPPERIDA.</EmptyState> : <><div className="table-scroll"><table><thead><tr><SortableHeader label="Indikator" column="indicator_code" sortBy={mappingSortBy} direction={mappingSortOrder} onSort={(column, direction) => { setMappingSortBy(column); setMappingSortOrder(direction); }} /><SortableHeader label="Sumber" column="source_code" sortBy={mappingSortBy} direction={mappingSortOrder} onSort={(column, direction) => { setMappingSortBy(column); setMappingSortOrder(direction); }} /><th>Kolom data</th><SortableHeader label="Status" column="status" sortBy={mappingSortBy} direction={mappingSortOrder} onSort={(column, direction) => { setMappingSortBy(column); setMappingSortOrder(direction); }} /><th>Tindakan Walidata</th></tr></thead><tbody>{sortedMappings.map((mapping) => <tr key={mapping.id}><td><strong>{mapping.indicator_code}</strong><small>{mapping.indicator_name}</small></td><td>{mapping.source_code}<small>{mapping.external_dataset_id}</small></td><td>{mapping.year_field} → {mapping.value_field}<small>Wilayah {mapping.geography_code || "-"}</small></td><td><Badge tone={mapping.status === "active" ? "success" : mapping.status === "draft" ? "warning" : "neutral"}>{mapping.status === "draft" ? "Perlu diperiksa" : mapping.status === "approved" ? "Siap diaktifkan" : mapping.status}</Badge></td><td><span className="table-actions">{canManage && mapping.status === "draft" && <button className="button secondary compact" onClick={() => void mappingAction(mapping, "approve")}>Tandai mapping sesuai</button>}{canManage && mapping.status === "approved" && <button className="button secondary compact" onClick={() => void mappingAction(mapping, "activate")}>Aktifkan aliran</button>}{canManage && ["approved", "active"].includes(mapping.status) && <button className="button primary compact" onClick={() => void mappingAction(mapping, "sync")}><Download />Periksa data masuk</button>}{!canManage && <small>Mode pantau</small>}</span></td></tr>)}</tbody></table></div><div className="table-static-summary">Menampilkan <strong>{sortedMappings.length}</strong> mapping · Urutan dapat diubah dari kepala tabel.</div></>}</section>
    {run && <section className="panel connector-run"><header className="panel-heading"><div><span className="eyebrow">Pemeriksaan sebelum impor</span><h2>Preview data masuk</h2><p>Belum ada data yang mengubah capaian. Periksa ringkasan dan baris bermasalah sebelum menyetujui impor.</p></div><CheckCircle2 /></header><div className="detail-grid"><div><span>Baris valid</span><strong>{run.preview_json.valid_rows ?? 0}</strong></div><div><span>Perlu diperbaiki</span><strong>{run.preview_json.invalid_rows ?? 0}</strong></div><div><span>Tahun data</span><strong>{(run.preview_json.years ?? []).join(", ") || "-"}</strong></div></div>{run.values.length > 0 && <div className="table-scroll"><table><thead><tr><SortableHeader label="Tahun" column="year" sortBy={previewSortBy} direction={previewSortOrder} onSort={(column, direction) => { setPreviewSortBy(column); setPreviewSortOrder(direction); }} /><SortableHeader label="Wilayah" column="geography_code" sortBy={previewSortBy} direction={previewSortOrder} onSort={(column, direction) => { setPreviewSortBy(column); setPreviewSortOrder(direction); }} /><th>Nilai</th><SortableHeader label="Hasil pemeriksaan" column="validation_status" sortBy={previewSortBy} direction={previewSortOrder} onSort={(column, direction) => { setPreviewSortBy(column); setPreviewSortOrder(direction); }} /></tr></thead><tbody>{sortedRunValues.map((item, index) => <tr key={`${item.year}-${item.geography_code}-${index}`}><td>{item.year}</td><td>{item.geography_code}</td><td>{item.numeric_value ?? item.text_value ?? "-"}</td><td>{item.validation_status}</td></tr>)}</tbody></table></div>}{run.status === "ready" && <div className="panel-actions"><button className="button primary" onClick={() => void importRun()}><Download />Impor data yang sudah diperiksa</button></div>}</section>}
    {integrationOpen && organizations.data && <IntegrationFormModal organizations={organizations.data.data} initial={editingIntegration} onClose={() => setIntegrationOpen(false)} onSaved={() => { setIntegrationOpen(false); integrations.reload(); }} />}
  </>;
}

function ConnectionProfileCard({ profile }: { profile: ConnectionProfile }) {
  return <div className="connection-profile"><strong>{profile.reachable ? "Terjangkau" : "Tidak terjangkau"}</strong><small>{profile.platform ?? profile.error ?? "Tidak ada identitas platform."} · {profile.response_ms ?? "-"} ms · {new Date(profile.checked_at).toLocaleString("id-ID")}</small>{profile.reachable && <><small>{profile.dataset_count ?? 0} dataset · {profile.resource_count ?? 0} resource terstruktur (CSV/JSON/XLS/XLSX/XML/API)</small><small>{profile.candidate_summary.annual_series_count ?? 0} kandidat tren tahunan · {profile.candidate_summary.structured_series_count ?? 0} dapat dibaca sebagai tabel · Publisher: {profile.publishers.join(", ") || "-"}</small></>}<small>Kandidat master approved/aktif: {profile.candidate_summary.candidate_count} · sudah mapping {profile.candidate_summary.mapped_count} · belum {profile.candidate_summary.unmapped_count} · ambigu {profile.candidate_summary.ambiguous_count}</small>{profile.candidate_summary.series_candidates?.slice(0, 3).map((candidate) => <small key={candidate.dataset_name}>Tren · {candidate.title} · {candidate.formats.join("/") || "format belum dikenali"}</small>)}{profile.candidate_summary.candidates.slice(0, 3).map((candidate) => <small key={`${candidate.type}-${candidate.code}-${candidate.source_title}`}>{candidate.status} · {candidate.name} · skor {candidate.score} · {candidate.reason}</small>)}</div>;
}

const connectorKindLabel = (kind: IntegrationForm["connector_kind"]) => ({ api_json: "API JSON", ckan: "Portal CKAN", bps: "BPS (publikasi/API)", csv_url: "CSV melalui URL", file_upload: "Unggah file berkala", database_view: "Database/View", html_scrape: "Website/scraping", manual: "Input manual" }[kind]);
const integrationStatusLabel = (status: IntegrationProfile["status"]) => ({ draft: "Draf", testing: "Pengujian", active: "Aktif", paused: "Dijeda", error: "Bermasalah" }[status]);
const syncScheduleLabel = (profile: IntegrationProfile) => profile.sync_mode === "manual" ? "Dijalankan manual" : profile.sync_interval_minutes === 60 ? "Setiap jam" : profile.sync_interval_minutes === 360 ? "Setiap 6 jam" : profile.sync_interval_minutes === 1440 ? "Setiap hari" : profile.sync_interval_minutes === 10080 ? "Setiap minggu" : profile.sync_interval_minutes === 44640 ? "Setiap bulan" : `Setiap ${profile.sync_interval_minutes ?? "-"} menit`;

function IntegrationFormModal({ organizations, initial, onClose, onSaved }: { organizations: Organization[]; initial: IntegrationProfile | null; onClose(): void; onSaved(): void }) {
  const [form, setForm] = useState<IntegrationForm>({
    organization_id: initial?.organization_id ?? organizations.find((item) => item.organization_type === "opd")?.id ?? "",
    code: initial?.code ?? "", name: initial?.name ?? "", connector_kind: initial?.connector_kind ?? "api_json",
    base_url: initial?.base_url ?? "", endpoint_path: initial?.endpoint_path ?? "", auth_type: initial?.auth_type ?? "none",
    data_format: initial?.data_format ?? "json", data_path: initial?.data_path ?? "", sync_mode: initial?.sync_mode ?? "manual",
    sync_interval_minutes: initial?.sync_interval_minutes ? String(initial.sync_interval_minutes) : "1440",
    verification_mode: initial?.verification_mode ?? "preview_required", status: initial?.status === "active" || initial?.status === "paused" ? initial.status : "draft",
    notes: initial?.notes ?? "",
  });
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const update = <K extends keyof IntegrationForm>(key: K, value: IntegrationForm[K]) => setForm((current) => ({ ...current, [key]: value }));
  const chooseKind = (kind: IntegrationForm["connector_kind"]) => setForm((current) => ({ ...current, connector_kind: kind,
    data_format: kind === "api_json" || kind === "ckan" || kind === "bps" ? "json" : kind === "csv_url" ? "csv" : kind === "file_upload" ? "xlsx" : kind === "database_view" ? "database" : kind === "html_scrape" ? "html" : "manual",
    auth_type: ["file_upload", "manual"].includes(kind) ? "none" : current.auth_type,
  }));
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setBusy(true); setError("");
    try {
      const payload = { ...form, code: form.code.trim().toUpperCase().replace(/\s+/gu, "_"), base_url: form.base_url.trim() || null, endpoint_path: form.endpoint_path.trim() || null, data_path: form.data_path.trim() || null, notes: form.notes.trim() || null, sync_interval_minutes: form.sync_mode === "scheduled" ? Number(form.sync_interval_minutes) : null };
      await api(initial ? `/connectors/integrations/${initial.id}` : "/connectors/integrations", { method: initial ? "PUT" : "POST", mutation: true, body: jsonBody(payload) });
      onSaved();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Profil sumber gagal disimpan."); }
    finally { setBusy(false); }
  };
  const urlRequired = !["file_upload", "manual"].includes(form.connector_kind);
  return <Modal title={initial ? "Pengaturan sumber data" : "Daftarkan sumber data OPD"} onClose={onClose} wide>{error && <Notice tone="error">{error}</Notice>}<form className="form-stack integration-form" onSubmit={submit}>
    <div className="form-section"><header><span>1</span><div><strong>Identitas sumber</strong><small>Tetapkan sistem ini milik OPD mana.</small></div></header><div className="form-grid"><label className="field"><span>OPD pemilik</span><select value={form.organization_id} onChange={(event) => update("organization_id", event.target.value)} required><option value="">Pilih OPD</option>{organizations.filter((item) => item.organization_type === "opd").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="field"><span>Nama sumber</span><input value={form.name} onChange={(event) => update("name", event.target.value)} placeholder="Contoh: SIM Kesehatan Dinkes" required /></label><label className="field"><span>Kode sumber</span><input value={form.code} disabled={Boolean(initial)} onChange={(event) => update("code", event.target.value.toUpperCase().replace(/\s+/gu, "_"))} placeholder="SIMKES_DINKES" required /></label></div></div>
    <div className="form-section"><header><span>2</span><div><strong>Cara mengambil data</strong><small>Pilih teknologi yang benar; setiap website OPD boleh berbeda.</small></div></header><div className="connector-kind-grid">{(["api_json","ckan","bps","csv_url","file_upload","database_view","html_scrape","manual"] as const).map((kind) => <button className={form.connector_kind === kind ? "selected" : ""} type="button" key={kind} onClick={() => chooseKind(kind)}><Database /><span><strong>{connectorKindLabel(kind)}</strong><small>{kind === "html_scrape" ? "Pilihan terakhir jika tidak ada API" : kind === "manual" ? "Untuk sumber yang belum digital" : "Sumber terstruktur"}</small></span></button>)}</div><div className="form-grid"><label className="field connector-wide"><span>Alamat utama sumber {urlRequired ? "" : "(opsional)"}</span><input type="url" value={form.base_url} onChange={(event) => update("base_url", event.target.value)} placeholder="https://domain-opd.kapuaskab.go.id" required={urlRequired} /></label><label className="field"><span>Path endpoint/resource</span><input value={form.endpoint_path} onChange={(event) => update("endpoint_path", event.target.value)} placeholder="/api/v1/capaian" /></label><label className="field"><span>Lokasi array data</span><input value={form.data_path} onChange={(event) => update("data_path", event.target.value)} placeholder="data.items (jika ada)" /></label><label className="field"><span>Format data</span><select value={form.data_format} onChange={(event) => update("data_format", event.target.value as IntegrationForm["data_format"])}><option value="json">JSON</option><option value="csv">CSV</option><option value="xlsx">Excel/XLSX</option><option value="html">HTML</option><option value="database">Database</option><option value="manual">Manual</option></select></label><label className="field"><span>Autentikasi</span><select value={form.auth_type} onChange={(event) => update("auth_type", event.target.value as IntegrationForm["auth_type"])}><option value="none">Tanpa kredensial</option><option value="api_key">API key</option><option value="bearer">Bearer token</option><option value="basic">Username & password</option><option value="oauth2">OAuth 2.0</option></select><small>Kredensial rahasia diatur terpisah oleh Developer.</small></label></div></div>
    <div className="form-section"><header><span>3</span><div><strong>Jadwal dan pengamanan</strong><small>Atur kapan data diperiksa dan apakah perlu persetujuan manusia.</small></div></header><div className="form-grid"><label className="field"><span>Mode sinkronisasi</span><select value={form.sync_mode} onChange={(event) => update("sync_mode", event.target.value as IntegrationForm["sync_mode"])}><option value="manual">Manual oleh Walidata</option><option value="scheduled">Terjadwal otomatis</option></select></label>{form.sync_mode === "scheduled" && <label className="field"><span>Interval</span><select value={form.sync_interval_minutes} onChange={(event) => update("sync_interval_minutes", event.target.value)}><option value="60">Setiap jam</option><option value="360">Setiap 6 jam</option><option value="1440">Setiap hari</option><option value="10080">Setiap minggu</option><option value="44640">Setiap bulan</option></select></label>}<label className="field"><span>Setelah data ditemukan</span><select value={form.verification_mode} onChange={(event) => update("verification_mode", event.target.value as IntegrationForm["verification_mode"])}><option value="preview_required">Wajib preview dan persetujuan</option><option value="auto_import">Impor otomatis jika valid</option></select></label><label className="field"><span>Status konfigurasi</span><select value={form.status} onChange={(event) => update("status", event.target.value as IntegrationForm["status"])}><option value="draft">Draf — belum dijalankan</option><option value="active">Aktif</option><option value="paused">Dijeda</option></select></label></div><label className="field"><span>Catatan teknis</span><textarea rows={3} value={form.notes} onChange={(event) => update("notes", event.target.value)} placeholder="PIC teknis, batasan akses, atau ketentuan pembaruan data." /></label><Notice tone="warning">Untuk tahap awal, gunakan “Wajib preview dan persetujuan”. Impor otomatis sebaiknya diaktifkan setelah hasil sinkronisasi stabil dan telah diuji Walidata.</Notice></div>
    <footer className="modal-actions"><button className="button secondary" type="button" onClick={onClose}>Batal</button><button className="button primary" disabled={busy}>{busy ? "Menyimpan…" : "Simpan profil sumber"}</button></footer>
  </form></Modal>;
}
