import { CheckCircle2, CloudCog, Download, Link2, Search, ShieldAlert } from "lucide-react";
import { useState } from "react";
import { api, jsonBody } from "../api";
import { useAuth } from "../auth";
import { Badge, EmptyState, Notice, Spinner, useAsync } from "../components";
import type { Indicator, PageResponse } from "../types";

interface Candidate { type: "category" | "indicator"; code: string; name: string; source_title: string; score: number; reason: string; status: "mapped" | "unmapped" | "ambiguous" }
interface ConnectionProfile { source_code: string; reachable: boolean; response_ms: number | null; platform: string | null; dataset_count: number | null; resource_count: number | null; publishers: string[]; years: number[]; checked_at: string; error: string | null; candidate_summary: { candidate_count: number; mapped_count: number; unmapped_count: number; ambiguous_count: number; candidates: Candidate[] } }
interface SourceStatus { code: string; name: string; source_type: string; base_url: string; status: string; status_message?: string }
interface CkanResource { id: string; name: string; format?: string; url: string; datastore_active?: boolean }
interface CkanPackage { id: string; name: string; title: string; notes?: string; resources?: CkanResource[] }
interface Mapping { id: string; indicator_version_id: string; indicator_code: string; indicator_name: string; source_code: string; source_type: string; external_dataset_id: string; external_resource_id: string | null; resource_url: string | null; geography_code: string; year_field: string; value_field: string; status: string }
interface Run { id: string; status: string; preview_json: { rows_seen?: number; valid_rows?: number; invalid_rows?: number; years?: number[] }; values: Array<{ year: number; geography_code: string; numeric_value: string | null; text_value: string | null; validation_status: string; validation_errors: string[] }> }

const sourceLabel = (status: string) => status === "connected" ? "Terhubung" : status === "waiting_api_key" ? "Menunggu API key" : status === "error" ? "Perlu diperiksa" : status;

export function ConnectorsPage() {
  const { user } = useAuth();
  const canManage = user?.permissions.includes("connector.manage") ?? false;
  const sources = useAsync(() => api<{ data: SourceStatus[] }>("/connectors/status"), []);
  const indicators = useAsync(() => api<PageResponse<Indicator>>("/indicators?page=1&page_size=100&status=active"), []);
  const mappings = useAsync(() => api<{ data: Mapping[] }>("/connectors/mappings"), []);
  const [query, setQuery] = useState(""); const [search, setSearch] = useState(""); const [results, setResults] = useState<CkanPackage[]>([]); const [searchBusy, setSearchBusy] = useState(false); const [error, setError] = useState(""); const [run, setRun] = useState<Run | null>(null); const [profiles, setProfiles] = useState<Record<string, ConnectionProfile>>({}); const [profileBusy, setProfileBusy] = useState<string | null>(null);
  const [form, setForm] = useState({ indicator_version_id: "", source_code: "SATUDATA_KAPUAS", external_dataset_id: "", external_resource_id: "", resource_url: "", geography_field: "", geography_code: "6203", year_field: "tahun", value_field: "nilai", unit_field: "", expected_unit: "" });
  const searchCkan = async () => { setSearchBusy(true); setError(""); try { const result = await api<{ results: CkanPackage[] }>(`/connectors/ckan/search?q=${encodeURIComponent(query)}&rows=10`); setResults(result.results); } catch (cause) { setError(cause instanceof Error ? cause.message : "Katalog tidak dapat dicari."); } finally { setSearchBusy(false); } };
  const saveMapping = async () => { setError(""); try { await api("/connectors/mappings", { method: "POST", mutation: true, body: jsonBody({ ...form, external_resource_id: form.external_resource_id || null, resource_url: form.resource_url || null, geography_field: form.geography_field || null, unit_field: form.unit_field || null, expected_unit: form.expected_unit || null }) }); mappings.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Mapping gagal disimpan."); } };
  const mappingAction = async (mapping: Mapping, action: "approve" | "activate" | "sync") => {
    setError("");
    try {
      if (action === "sync") {
        const syncResult = await api<Run>(`/connectors/mappings/${mapping.id}/sync`, { method: "POST", mutation: true });
        setRun(syncResult);
      } else {
        await api<Mapping>(`/connectors/mappings/${mapping.id}/actions/${action}`, { method: "POST", mutation: true });
      }
      mappings.reload();
    } catch (cause) {
      setError(cause instanceof Error ? cause.message : "Aksi konektor gagal.");
    }
  };
  const importRun = async () => { if (!run) return; setError(""); try { setRun(await api<Run>(`/connectors/runs/${run.id}/import`, { method: "POST", mutation: true })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Import gagal."); } };
  const testConnection = async (sourceCode: "SATUDATA_KAPUAS" | "BPS_KAPUAS") => { setProfileBusy(sourceCode); setError(""); try { const profile = await api<ConnectionProfile>(`/connectors/${sourceCode}/test`, { method: "POST", mutation: true }); setProfiles((current) => ({ ...current, [sourceCode]: profile })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Uji koneksi gagal."); } finally { setProfileBusy(null); } };
  return <>
    {error && <Notice tone="error">{error}</Notice>}
    <section className="summary-grid connector-summary-grid">{sources.loading ? <Spinner /> : sources.data?.data.map((source) => <article className="summary-card connector-source-card" key={source.code}><span className="table-icon"><CloudCog /></span><div><small>{source.name}</small><strong>{sourceLabel(source.status)}</strong><p>{source.status_message ?? source.base_url}</p>{canManage && <button className="button secondary compact" onClick={() => void testConnection(source.code as "SATUDATA_KAPUAS" | "BPS_KAPUAS")} disabled={profileBusy === source.code}>{profileBusy === source.code ? "Menguji…" : "Uji koneksi"}</button>}{profiles[source.code] && <ConnectionProfileCard profile={profiles[source.code]!} />}</div></article>)}</section>
    <Notice tone="warning">Konektor hanya membaca data tahunan 2025-2029. Mapping harus eksplisit dan disetujui BAPPERIDA/Developer; tidak ada pencocokan judul otomatis.</Notice>
    {canManage && <section className="panel connector-panel"><header className="panel-heading"><div><span className="eyebrow">Pencarian katalog</span><h2>Cari dataset Satu Data Kapuas</h2><p>Hasil pencarian hanya menjadi kandidat. Data baru masuk setelah mapping disimpan dan disetujui.</p></div><Search /></header><div className="toolbar connector-toolbar"><input aria-label="Cari dataset" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Contoh: kesehatan, IKP, stunting" /><button className="button secondary" onClick={() => void searchCkan()} disabled={searchBusy}><Search />{searchBusy ? "Mencari…" : "Cari katalog"}</button></div>{results.length > 0 && <div className="candidate-list connector-results">{results.map((item) => <article key={item.id}><span><strong>{item.title}</strong><small>{item.name} · {item.resources?.length ?? 0} resource</small></span><button className="button secondary compact" onClick={() => { const resource = item.resources?.find((candidate) => ["CSV", "JSON"].includes((candidate.format ?? "").toUpperCase())); setForm((current) => ({ ...current, external_dataset_id: item.id, external_resource_id: resource?.id ?? "", resource_url: resource?.url ?? "" })); setSearch(item.id); }}>Pilih untuk mapping</button></article>)}</div>}</section>}
    {canManage && indicators.data && <section className="panel connector-panel"><header className="panel-heading"><div><span className="eyebrow">Mapping eksplisit</span><h2>Hubungkan sumber ke indikator aktif</h2><p>Nilai belum diimpor sebelum preview disetujui.</p></div><Link2 /></header><div className="form-grid connector-form"><label className="field"><span>Indikator</span><select value={form.indicator_version_id} onChange={(event) => setForm({ ...form, indicator_version_id: event.target.value })}><option value="">Pilih indikator</option>{indicators.data.data.map((item) => <option key={item.version_id} value={item.version_id}>{item.code} - {item.name}</option>)}</select></label><label className="field"><span>Sumber</span><select value={form.source_code} onChange={(event) => setForm({ ...form, source_code: event.target.value })}><option value="SATUDATA_KAPUAS">Satu Data Kapuas</option><option value="BPS_KAPUAS">BPS WebAPI</option></select></label><label className="field"><span>Dataset/package ID</span><input value={form.external_dataset_id} onChange={(event) => setForm({ ...form, external_dataset_id: event.target.value })} /></label><label className="field"><span>Resource ID</span><input value={form.external_resource_id} onChange={(event) => setForm({ ...form, external_resource_id: event.target.value })} /></label><label className="field connector-wide"><span>URL resource</span><input value={form.resource_url} onChange={(event) => setForm({ ...form, resource_url: event.target.value })} /></label><label className="field"><span>Kolom tahun</span><input value={form.year_field} onChange={(event) => setForm({ ...form, year_field: event.target.value })} /></label><label className="field"><span>Kolom nilai</span><input value={form.value_field} onChange={(event) => setForm({ ...form, value_field: event.target.value })} /></label><label className="field"><span>Kolom wilayah</span><input value={form.geography_field} onChange={(event) => setForm({ ...form, geography_field: event.target.value })} placeholder="Kosong jika dataset khusus Kapuas" /></label><label className="field"><span>Kode wilayah</span><input value={form.geography_code} onChange={(event) => setForm({ ...form, geography_code: event.target.value })} /></label></div><div className="panel-actions"><button className="button primary" disabled={!form.indicator_version_id || !form.external_dataset_id} onClick={() => void saveMapping()}><Link2 />Simpan sebagai draf</button></div></section>}
    <section className="panel table-panel connector-panel"><header className="panel-heading"><div><span className="eyebrow">Mapping dan sinkronisasi</span><h2>Daftar mapping sumber</h2><p>Mapping diurutkan berdasarkan indikator.</p></div><ShieldAlert /></header>{mappings.loading ? <div className="panel-loading"><Spinner /></div> : !mappings.data?.data.length ? <EmptyState title="Belum ada mapping">Buat mapping eksplisit dari indikator aktif ke dataset sumber.</EmptyState> : <><div className="table-scroll"><table><thead><tr><th>Indikator</th><th>Sumber</th><th>Kolom data</th><th>Status</th><th>Tindakan</th></tr></thead><tbody>{mappings.data.data.map((mapping) => <tr key={mapping.id}><td><strong>{mapping.indicator_code}</strong><small>{mapping.indicator_name}</small></td><td>{mapping.source_code}<small>{mapping.external_dataset_id}</small></td><td>{mapping.year_field} → {mapping.value_field}<small>Wilayah {mapping.geography_code || "-"}</small></td><td><Badge tone={mapping.status === "active" ? "success" : mapping.status === "draft" ? "warning" : "neutral"}>{mapping.status}</Badge></td><td><span className="table-actions">{mapping.status === "draft" && <button className="button secondary compact" onClick={() => void mappingAction(mapping, "approve")}>Setujui</button>}{mapping.status === "approved" && <button className="button secondary compact" onClick={() => void mappingAction(mapping, "activate")}>Aktifkan</button>}{["approved", "active"].includes(mapping.status) && <button className="button primary compact" onClick={() => void mappingAction(mapping, "sync")}><Download />Preview sinkronisasi</button>}</span></td></tr>)}</tbody></table></div><div className="table-static-summary">Menampilkan <strong>{mappings.data.data.length}</strong> dari <strong>{mappings.data.data.length}</strong> mapping · Urutan: <strong>Indikator</strong></div></>}</section>
    {run && <section className="panel"><header className="panel-heading"><div><span className="eyebrow">Preview hasil fetch</span><h2>Run {run.id}</h2><p>Status {run.status}. Nilai masih staging sampai tombol import ditekan.</p></div><CheckCircle2 /></header><div className="detail-grid"><div><span>Baris valid</span><strong>{run.preview_json.valid_rows ?? 0}</strong></div><div><span>Baris invalid</span><strong>{run.preview_json.invalid_rows ?? 0}</strong></div><div><span>Tahun</span><strong>{(run.preview_json.years ?? []).join(", ") || "-"}</strong></div></div>{run.values.length > 0 && <div className="table-scroll"><table><thead><tr><th>Tahun</th><th>Wilayah</th><th>Nilai</th><th>Status validasi</th></tr></thead><tbody>{run.values.map((item, index) => <tr key={`${item.year}-${item.geography_code}-${index}`}><td>{item.year}</td><td>{item.geography_code}</td><td>{item.numeric_value ?? item.text_value ?? "-"}</td><td>{item.validation_status}</td></tr>)}</tbody></table></div>}{run.status === "ready" && <button className="button primary" onClick={() => void importRun()}><Download />Setujui import ke observasi baru</button>}</section>}
  </>;
}

function ConnectionProfileCard({ profile }: { profile: ConnectionProfile }) {
  return <div className="connection-profile"><strong>{profile.reachable ? "Terjangkau" : "Tidak terjangkau"}</strong><small>{profile.platform ?? profile.error ?? "Tidak ada identitas platform."} · {profile.response_ms ?? "-"} ms · {new Date(profile.checked_at).toLocaleString("id-ID")}</small>{profile.reachable && <small>{profile.dataset_count ?? 0} dataset · {profile.resource_count ?? 0} resource CSV/JSON/API · Publisher: {profile.publishers.join(", ") || "-"} · Tahun: {profile.years.join(", ") || "-"}</small>}<small>Kandidat master approved/aktif: {profile.candidate_summary.candidate_count} · sudah mapping {profile.candidate_summary.mapped_count} · belum {profile.candidate_summary.unmapped_count} · ambigu {profile.candidate_summary.ambiguous_count}</small>{profile.candidate_summary.candidates.slice(0, 5).map((candidate) => <small key={`${candidate.type}-${candidate.code}-${candidate.source_title}`}>{candidate.status} · {candidate.name} · skor {candidate.score} · {candidate.reason}</small>)}</div>;
}
