import { ArrowLeft, BadgeCheck, Database, Download, FileText, Globe2, Plus, Save, Send, Trash2, Upload, UserRound } from "lucide-react";
import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from "react";
import { api, apiPath, jsonBody } from "../api";
import { useAuth } from "../auth";
import { Badge, EmptyState, Notice, PageLoading, useAsync } from "../components";

type Status = "draft" | "submitted" | "returned" | "verified";
interface ProfileSummary {
  id: string | null; organization_id: string; organization_code: string; organization_name: string;
  response_json: ProfileResponse; technical_status: Status; planning_status: Status;
  technical_notes: string | null; planning_notes: string | null; document_count?: number; updated_at: string | null;
}
interface DocumentItem { id: string; document_type: string; document_year: number | null; original_filename: string; mime_type: string; byte_size: string; uploaded_at: string }
interface BaselineItem { id: string; plan_type: "rpjmd" | "renstra"; indicator_code: string; indicator_name: string; period: string; target: string; realization: string; unit: string; source: string; notes: string }
interface ProfileResponse {
  pic?: { name?: string; position?: string; email?: string; whatsapp?: string };
  website?: { has_website?: "yes" | "no" | "unknown"; url?: string; active_status?: string; managed_by?: string };
  integration?: { api_available?: string; api_endpoint?: string; export_formats?: string[]; update_frequency?: string; internal_database?: string };
  data_management?: { rpjmd_on_website?: string; renstra_on_website?: string; storage_locations?: string[]; internal_systems?: string; responsible_unit?: string };
  baseline_items?: BaselineItem[]; declaration?: { accurate?: boolean };
}

const emptyResponse = (): ProfileResponse => ({
  pic: { name: "", position: "", email: "", whatsapp: "" },
  website: { has_website: "unknown", url: "", active_status: "unknown", managed_by: "unknown" },
  integration: { api_available: "unknown", api_endpoint: "", export_formats: [], update_frequency: "unknown", internal_database: "" },
  data_management: { rpjmd_on_website: "unknown", renstra_on_website: "unknown", storage_locations: [], internal_systems: "", responsible_unit: "" },
  baseline_items: [], declaration: { accurate: false },
});
function normalizeResponse(value: ProfileResponse): ProfileResponse {
  const empty = emptyResponse();
  return {
    pic: { ...empty.pic, name: value.pic?.name, position: value.pic?.position, email: value.pic?.email, whatsapp: value.pic?.whatsapp },
    website: { ...empty.website, has_website: value.website?.has_website, url: value.website?.url, active_status: value.website?.active_status, managed_by: value.website?.managed_by },
    integration: { ...empty.integration, api_available: value.integration?.api_available, api_endpoint: value.integration?.api_endpoint, export_formats: value.integration?.export_formats ?? [], update_frequency: value.integration?.update_frequency, internal_database: value.integration?.internal_database },
    data_management: { ...empty.data_management, rpjmd_on_website: value.data_management?.rpjmd_on_website, renstra_on_website: value.data_management?.renstra_on_website, storage_locations: value.data_management?.storage_locations ?? [], internal_systems: value.data_management?.internal_systems, responsible_unit: value.data_management?.responsible_unit },
    baseline_items: value.baseline_items ?? [], declaration: { accurate: Boolean(value.declaration?.accurate) },
  };
}
const newBaseline = (): BaselineItem => ({ id: crypto.randomUUID(), plan_type: "rpjmd", indicator_code: "", indicator_name: "", period: "", target: "", realization: "", unit: "", source: "", notes: "" });
const statusLabel = (value: Status) => ({ draft: "Draf", submitted: "Menunggu pemeriksaan", returned: "Perlu perbaikan", verified: "Terverifikasi" }[value]);
const statusTone = (value: Status) => value === "verified" ? "success" : value === "returned" ? "danger" : value === "submitted" ? "warning" : "neutral";
const documentLabel: Record<string, string> = { renstra: "Dokumen Renstra", rpjmd_progress: "Dokumen atau laporan perkembangan RPJMD" };

export function OpdProfilePage() {
  const { user } = useAuth();
  const list = useAsync(() => api<{ data: ProfileSummary[]; can_review_technical: boolean; can_review_planning: boolean }>("/opd-profiles"), []);
  const [organizationId, setOrganizationId] = useState("");
  const [profile, setProfile] = useState<ProfileSummary | null>(null);
  const [form, setForm] = useState<ProfileResponse>(emptyResponse());
  const [documents, setDocuments] = useState<DocumentItem[]>([]);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  const [uploadType, setUploadType] = useState("renstra"); const [uploadYear, setUploadYear] = useState(String(new Date().getFullYear())); const [uploadFile, setUploadFile] = useState<File | null>(null);
  const [reviewNotes, setReviewNotes] = useState("");
  const mayEditSelected = Boolean(user?.roles.some((item) => item.code === "superadmin") || user?.organizations.some((item) => item.id === organizationId));
  const editable = mayEditSelected && (!profile || (["draft", "returned"].includes(profile.technical_status) && ["draft", "returned"].includes(profile.planning_status)));

  useEffect(() => {
    if (!organizationId && list.data?.data.length) {
      const own = list.data.data.find((item) => user?.organizations.some((org) => org.id === item.organization_id));
      setOrganizationId((own ?? list.data.data[0]!).organization_id);
    }
  }, [list.data, organizationId, user?.organizations]);
  useEffect(() => {
    if (!organizationId) return;
    setError(""); setMessage("");
    void Promise.all([api<ProfileSummary>(`/opd-profiles/${organizationId}`), api<{ data: DocumentItem[] }>(`/opd-profiles/${organizationId}/documents`)]).then(([next, docs]) => {
      setProfile(next); setForm(normalizeResponse(next.response_json)); setDocuments(docs.data);
    }).catch((cause) => setError(cause instanceof Error ? cause.message : "Profil OPD gagal dimuat."));
  }, [organizationId]);

  const setSection = (section: "pic" | "website" | "integration" | "data_management" | "declaration", key: string, value: unknown) => setForm((current) => ({ ...current, [section]: { ...(current[section] ?? {}), [key]: value } }));
  const toggleArray = (section: "integration" | "data_management", value: string) => setForm((current) => {
    const existing = section === "integration" ? (current.integration?.export_formats ?? []) : (current.data_management?.storage_locations ?? []);
    const values = existing.includes(value) ? existing.filter((item) => item !== value) : [...existing, value];
    return section === "integration" ? { ...current, integration: { ...current.integration, export_formats: values } } : { ...current, data_management: { ...current.data_management, storage_locations: values } };
  });
  const updateBaseline = (id: string, key: keyof BaselineItem, value: string) => setForm((current) => ({ ...current, baseline_items: (current.baseline_items ?? []).map((item) => item.id === id ? { ...item, [key]: value } : item) }));
  const save = async () => { setBusy(true); setError(""); setMessage(""); try { const next = await api<ProfileSummary>(`/opd-profiles/${organizationId}`, { method: "PUT", mutation: true, body: jsonBody({ response: normalizeResponse(form) }) }); setProfile(next); setMessage("Draf profil dan baseline berhasil disimpan."); list.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Formulir gagal disimpan."); } finally { setBusy(false); } };
  const submit = async () => { setBusy(true); setError(""); try { const next = await api<ProfileSummary>(`/opd-profiles/${organizationId}/submit`, { method: "POST", mutation: true }); setProfile(next); setMessage("Formulir dikirim ke Diskominfosantik dan BAPPERIDA."); list.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Formulir gagal dikirim."); } finally { setBusy(false); } };
  const upload = async (event: FormEvent) => { event.preventDefault(); if (!uploadFile) return; setBusy(true); setError(""); try { const data = new FormData(); data.append("file", uploadFile); await api(`/opd-profiles/${organizationId}/documents?document_type=${uploadType}&year=${uploadYear}`, { method: "POST", mutation: true, body: data }); const docs = await api<{ data: DocumentItem[] }>(`/opd-profiles/${organizationId}/documents`); setDocuments(docs.data); setUploadFile(null); setMessage("Dokumen berhasil diunggah."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Dokumen gagal diunggah."); } finally { setBusy(false); } };
  const review = async (track: "technical" | "planning", decision: "verify" | "return") => { setBusy(true); setError(""); try { const next = await api<ProfileSummary>(`/opd-profiles/${organizationId}/review/${track}/${decision}`, { method: "POST", mutation: true, body: jsonBody({ notes: reviewNotes.trim() || null }) }); setProfile(next); setReviewNotes(""); setMessage("Keputusan pemeriksaan tersimpan."); list.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Keputusan gagal disimpan."); } finally { setBusy(false); } };
  const completion = useMemo(() => { const checks = [form.pic?.name, form.pic?.whatsapp, form.pic?.position, form.website?.has_website !== "unknown", form.integration?.api_available !== "unknown", form.data_management?.rpjmd_on_website !== "unknown", form.data_management?.renstra_on_website !== "unknown", form.data_management?.storage_locations?.length, form.declaration?.accurate]; return Math.round(checks.filter(Boolean).length / checks.length * 100); }, [form]);

  if (list.loading) return <PageLoading label="Memuat profil data OPD" />;
  if (list.error || !list.data) return <Notice tone="error">{list.error ?? "Profil data OPD belum tersedia."}</Notice>;
  return <div className="opd-profile-page">
    {error && <Notice tone="error">{error}</Notice>}{message && <Notice tone="success">{message}</Notice>}
    <section className="panel opd-profile-intro"><div><span className="eyebrow">Pemetaan awal OPD</span><h2>Profil sumber data RPJMD dan Renstra</h2><p>Isi informasi inti satu kali. Capaian berkala tetap diperbarui melalui Pelaporan Realisasi agar tidak terjadi input ganda.</p></div><div className="completion-meter"><strong>{completion}%</strong><small>Kelengkapan inti</small><span><i style={{ width: `${completion}%` }} /></span></div></section>
    <section className="panel opd-profile-selector"><label className="field"><span>Perangkat daerah</span><select value={organizationId} onChange={(event) => setOrganizationId(event.target.value)}>{list.data.data.map((item) => <option key={item.organization_id} value={item.organization_id}>{item.organization_name}</option>)}</select></label>{profile && <div className="dual-review-status"><span><small>Teknis · Diskominfosantik</small><Badge tone={statusTone(profile.technical_status)}>{statusLabel(profile.technical_status)}</Badge></span><span><small>Substansi · BAPPERIDA</small><Badge tone={statusTone(profile.planning_status)}>{statusLabel(profile.planning_status)}</Badge></span></div>}</section>
    {profile?.technical_notes && <Notice tone="warning">Catatan teknis: {profile.technical_notes}</Notice>}{profile?.planning_notes && <Notice tone="warning">Catatan substansi: {profile.planning_notes}</Notice>}
    <fieldset disabled={!editable || busy} className="opd-profile-form">
      <ProfileSection number="1" icon={<UserRound />} title="PIC OPD" description="Kontak resmi yang bertanggung jawab atas isian dan konfirmasi data."><div className="form-grid"><Field label="Nama lengkap PIC" value={form.pic?.name} onChange={(v) => setSection("pic", "name", v)} required /><Field label="Jabatan/posisi" value={form.pic?.position} onChange={(v) => setSection("pic", "position", v)} required /><Field label="Email dinas" type="email" value={form.pic?.email} onChange={(v) => setSection("pic", "email", v)} /><Field label="Nomor WhatsApp aktif" type="tel" value={form.pic?.whatsapp} onChange={(v) => setSection("pic", "whatsapp", v)} required placeholder="08xxxxxxxxxx" /></div></ProfileSection>
      <ProfileSection number="2" icon={<Globe2 />} title="Website OPD" description="Informasi minimum untuk menilai apakah data dapat diambil dari website."><div className="form-grid"><SelectField label="Apakah OPD memiliki website?" value={form.website?.has_website} onChange={(v) => setSection("website", "has_website", v)} options={[["unknown","Pilih jawaban"],["yes","Ya"],["no","Tidak ada"]]} /><Field label="Alamat website" type="url" value={form.website?.url} onChange={(v) => setSection("website", "url", v)} disabled={form.website?.has_website !== "yes"} /><SelectField label="Kondisi website" value={form.website?.active_status} onChange={(v) => setSection("website", "active_status", v)} options={[["unknown","Belum diperiksa"],["active","Aktif dan diperbarui"],["stale","Aktif tetapi jarang diperbarui"],["down","Tidak dapat diakses"]]} /><SelectField label="Pengelola website" value={form.website?.managed_by} onChange={(v) => setSection("website", "managed_by", v)} options={[["unknown","Belum diketahui"],["opd","Tim OPD"],["kominfo","Diskominfosantik"],["vendor","Pihak ketiga"],["shared","OPD bersama Diskominfosantik"]]} /></div></ProfileSection>
      <ProfileSection number="3" icon={<Database />} title="Akses dan pembaruan data" description="Menentukan apakah integrasi dapat otomatis atau memerlukan unggah file."><div className="form-grid"><SelectField label="Apakah tersedia API?" value={form.integration?.api_available} onChange={(v) => setSection("integration", "api_available", v)} options={[["unknown","Belum diketahui"],["yes","Ya"],["no","Tidak tersedia"],["planned","Direncanakan"]]} /><Field label="Alamat API" type="url" value={form.integration?.api_endpoint} onChange={(v) => setSection("integration", "api_endpoint", v)} disabled={form.integration?.api_available !== "yes"} /><SelectField label="Frekuensi pembaruan data" value={form.integration?.update_frequency} onChange={(v) => setSection("integration", "update_frequency", v)} options={[["unknown","Belum diketahui"],["realtime","Real-time"],["daily","Harian"],["weekly","Mingguan"],["monthly","Bulanan"],["quarterly","Triwulanan"],["semester","Semesteran"],["annual","Tahunan"],["ad_hoc","Tidak tetap"]]} /><Field label="Aplikasi atau database internal" value={form.integration?.internal_database} onChange={(v) => setSection("integration", "internal_database", v)} placeholder="Nama sistem saja, jangan tulis password" /></div><CheckGroup title="Format data yang dapat diberikan" values={form.integration?.export_formats ?? []} options={[["json","JSON"],["csv","CSV"],["xlsx","Excel"],["pdf","PDF"],["none","Tidak tersedia"]]} onToggle={(value) => toggleArray("integration", value)} /></ProfileSection>
      <ProfileSection number="4" icon={<FileText />} title="Lokasi data RPJMD dan Renstra" description="Tunjukkan tempat data dikelola jika belum tersedia di website."><div className="form-grid"><SelectField label="Data RPJMD di website" value={form.data_management?.rpjmd_on_website} onChange={(v) => setSection("data_management", "rpjmd_on_website", v)} options={[["unknown","Belum diketahui"],["all","Ya, lengkap"],["some","Sebagian"],["no","Tidak dipublikasikan"]]} /><SelectField label="Data Renstra di website" value={form.data_management?.renstra_on_website} onChange={(v) => setSection("data_management", "renstra_on_website", v)} options={[["unknown","Belum diketahui"],["all","Ya, lengkap"],["some","Sebagian"],["no","Tidak dipublikasikan"]]} /><Field label="Aplikasi/sistem penyimpanan" value={form.data_management?.internal_systems} onChange={(v) => setSection("data_management", "internal_systems", v)} /><Field label="Bidang/unit pemilik data" value={form.data_management?.responsible_unit} onChange={(v) => setSection("data_management", "responsible_unit", v)} /></div><CheckGroup title="Lokasi penyimpanan saat ini" values={form.data_management?.storage_locations ?? []} options={[["website","Website OPD"],["satudata","Satu Data Kapuas"],["internal_app","Aplikasi internal"],["internal_db","Database internal"],["excel","Excel/Google Sheet"],["paper","Dokumen fisik"]]} onToggle={(value) => toggleArray("data_management", value)} /></ProfileSection>
      <ProfileSection number="5" icon={<BadgeCheck />} title="Baseline RPJMD dan Renstra" description="Masukkan capaian terakhir yang dapat dipertanggungjawabkan untuk dipetakan oleh BAPPERIDA."><div className="baseline-toolbar"><p>Satu baris untuk satu indikator dan satu periode.</p><button type="button" className="button secondary compact" onClick={() => setForm((current) => ({ ...current, baseline_items: [...(current.baseline_items ?? []), newBaseline()] }))}><Plus />Tambah indikator</button></div>{!form.baseline_items?.length ? <EmptyState title="Belum ada baseline">Tambahkan indikator RPJMD atau Renstra beserta target dan realisasi terakhir.</EmptyState> : <div className="baseline-list">{form.baseline_items.map((item, index) => <article key={item.id}><header><strong>Indikator {index + 1}</strong><button type="button" className="icon-button danger-text" aria-label="Hapus indikator" onClick={() => setForm((current) => ({ ...current, baseline_items: current.baseline_items?.filter((row) => row.id !== item.id) }))}><Trash2 /></button></header><div className="form-grid"><SelectField label="Dokumen acuan" value={item.plan_type} onChange={(v) => updateBaseline(item.id, "plan_type", v)} options={[["rpjmd","RPJMD"],["renstra","Renstra OPD"]]} /><Field label="Kode indikator (jika ada)" value={item.indicator_code} onChange={(v) => updateBaseline(item.id, "indicator_code", v)} /><Field label="Nama indikator" value={item.indicator_name} onChange={(v) => updateBaseline(item.id, "indicator_name", v)} required /><Field label="Periode" value={item.period} onChange={(v) => updateBaseline(item.id, "period", v)} placeholder="2025 / Triwulan IV 2025" required /><Field label="Target" value={item.target} onChange={(v) => updateBaseline(item.id, "target", v)} /><Field label="Realisasi" value={item.realization} onChange={(v) => updateBaseline(item.id, "realization", v)} /><Field label="Satuan" value={item.unit} onChange={(v) => updateBaseline(item.id, "unit", v)} /><Field label="Sumber data" value={item.source} onChange={(v) => updateBaseline(item.id, "source", v)} /><label className="field connector-wide"><span>Catatan singkat</span><textarea rows={2} value={item.notes} onChange={(event) => updateBaseline(item.id, "notes", event.target.value)} /></label></div></article>)}</div>}</ProfileSection>
      <ProfileSection number="6" icon={<Upload />} title="Dokumen acuan" description="Unggah hanya dokumen RPJMD atau Renstra. Maksimal 10 MB per file."><form className="document-upload" onSubmit={(event) => void upload(event)}><label className="field"><span>Jenis dokumen</span><select value={uploadType} onChange={(event) => setUploadType(event.target.value)}>{Object.entries(documentLabel).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><Field label="Tahun dokumen" type="number" value={uploadYear} onChange={setUploadYear} /><label className="field"><span>Pilih PDF, DOCX, atau XLSX</span><input type="file" accept=".pdf,.docx,.xlsx" onChange={(event) => setUploadFile(event.target.files?.[0] ?? null)} /></label><button className="button secondary" disabled={!profile?.id || !uploadFile || busy}><Upload />Unggah</button></form>{!documents.filter((item) => item.document_type in documentLabel).length ? <EmptyState title="Belum ada dokumen">Simpan draf terlebih dahulu, lalu unggah dokumen acuan.</EmptyState> : <div className="document-list">{documents.filter((item) => item.document_type in documentLabel).map((item) => <div key={item.id}><FileText /><span><strong>{documentLabel[item.document_type]}</strong><small>{item.original_filename} · {item.document_year ?? "Tanpa tahun"} · {(Number(item.byte_size)/1024/1024).toLocaleString("id-ID",{maximumFractionDigits:2})} MB</small></span><a className="button secondary compact" href={apiPath(`/opd-profiles/${organizationId}/documents/${item.id}/download`)}><Download />Unduh</a></div>)}</div>}</ProfileSection>
      <section className="panel declaration-panel"><label><input type="checkbox" checked={Boolean(form.declaration?.accurate)} onChange={(event) => setSection("declaration", "accurate", event.target.checked)} /><span><strong>Saya menyatakan informasi dan baseline sesuai dokumen atau sumber yang dikuasai OPD.</strong><small>Formulir dapat diperbaiki jika pemeriksa mengembalikannya.</small></span></label></section>
    </fieldset>
    {editable && <div className="sticky-form-actions"><span><strong>Simpan draf sebelum mengirim</strong><small>Formulir terkunci sementara selama pemeriksaan.</small></span><button className="button secondary" disabled={busy} onClick={() => void save()}><Save />Simpan draf</button><button className="button primary" disabled={busy || !profile?.id || !form.declaration?.accurate} onClick={() => void submit()}><Send />Kirim untuk diperiksa</button></div>}
    {profile?.technical_status === "submitted" && list.data.can_review_technical && <ReviewPanel title="Pemeriksaan teknis Diskominfosantik" notes={reviewNotes} setNotes={setReviewNotes} busy={busy} onVerify={() => void review("technical","verify")} onReturn={() => void review("technical","return")} />}
    {profile?.planning_status === "submitted" && list.data.can_review_planning && <ReviewPanel title="Pemeriksaan substansi BAPPERIDA" notes={reviewNotes} setNotes={setReviewNotes} busy={busy} onVerify={() => void review("planning","verify")} onReturn={() => void review("planning","return")} />}
  </div>;
}

function ProfileSection({ number, icon, title, description, children }: { number: string; icon: ReactNode; title: string; description: string; children: ReactNode }) { return <section className="panel opd-profile-section"><header><span>{icon}</span><div><small>Bagian {number}</small><h2>{title}</h2><p>{description}</p></div></header><div className="opd-section-body">{children}</div></section>; }
function Field({ label, value, onChange, type="text", required=false, disabled=false, placeholder="" }: { label: string; value?: string; onChange(value: string): void; type?: string; required?: boolean; disabled?: boolean; placeholder?: string }) { return <label className="field"><span>{label}{required && " *"}</span><input type={type} value={value ?? ""} onChange={(event) => onChange(event.target.value)} required={required} disabled={disabled} placeholder={placeholder} /></label>; }
function SelectField({ label, value, onChange, options }: { label: string; value?: string; onChange(value: string): void; options: Array<[string,string]> }) { return <label className="field"><span>{label}</span><select value={value ?? ""} onChange={(event) => onChange(event.target.value)}>{options.map(([key,label]) => <option key={key} value={key}>{label}</option>)}</select></label>; }
function CheckGroup({ title, values, options, onToggle }: { title: string; values: string[]; options: Array<[string,string]>; onToggle(value: string): void }) { return <fieldset className="check-group"><legend>{title}</legend>{options.map(([value,label]) => <label key={value}><input type="checkbox" checked={values.includes(value)} onChange={() => onToggle(value)} /><span>{label}</span></label>)}</fieldset>; }
function ReviewPanel({ title, notes, setNotes, busy, onVerify, onReturn }: { title: string; notes: string; setNotes(value:string):void; busy:boolean; onVerify():void; onReturn():void }) { return <section className="panel opd-review-panel"><header><div><span className="eyebrow">Keputusan pemeriksa</span><h2>{title}</h2></div></header><label className="field"><span>Catatan pemeriksaan</span><textarea rows={3} value={notes} onChange={(event) => setNotes(event.target.value)} placeholder="Wajib diisi jika dikembalikan." /></label><footer><button className="button secondary" disabled={busy || !notes.trim()} onClick={onReturn}><ArrowLeft />Kembalikan untuk diperbaiki</button><button className="button primary" disabled={busy} onClick={onVerify}><BadgeCheck />Tandai terverifikasi</button></footer></section>; }
