import { BadgeCheck, FilePlus2, Plus } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { api, jsonBody } from "../api";
import { useAuth } from "../auth";
import { Badge, EmptyState, Modal, Notice, Pagination, Spinner, statusLabel, useAsync } from "../components";
import type { PageResponse, Publication, PublicationCandidate } from "../types";

const cleanDisplayText = (value: string) => value.replace(/[–—]/gu, "-");
const formatPublishedValue = (numericValue: string | null, textValue: string | null, unit?: string | null) => {
  if (textValue) return textValue;
  if (numericValue === null || numericValue === "") return "-";
  const numeric = Number(numericValue);
  const value = Number.isFinite(numeric) ? new Intl.NumberFormat("id-ID", { maximumFractionDigits: 4 }).format(numeric) : numericValue;
  return `${value}${unit ? ` ${unit}` : ""}`;
};

export function PublicationsPage() {
  const { user } = useAuth(); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [status, setStatus] = useState("");
  const [createOpen, setCreateOpen] = useState(false); const [selected, setSelected] = useState<Publication | null>(null);
  const [deepLinkId] = useState(() => new URLSearchParams(window.location.search).get("id"));
  const publications = useAsync(() => api<PageResponse<Publication>>(`/publications?page=${page}&page_size=${pageSize}${status ? `&status=${status}` : ""}`), [page, pageSize, status]);
  const canManage = user?.permissions.includes("publication.manage") ?? false;
  useEffect(() => { if (deepLinkId) void api<Publication>(`/publications/${deepLinkId}`).then(setSelected).catch(() => undefined); }, [deepLinkId]);
  return <>
    <div className="toolbar"><select aria-label="Filter status publikasi" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">Semua status</option><option value="draft">Draf</option><option value="active">Aktif</option><option value="replaced">Digantikan</option><option value="withdrawn">Ditarik</option></select>{canManage && <button className="button primary" onClick={() => setCreateOpen(true)}><Plus />Susun publikasi</button>}</div>
    <Notice tone="warning">Publikasi adalah gerbang resmi menuju dashboard pimpinan. Hanya form capaian OPD dengan status Capaian disetujui yang dapat dipilih.</Notice>
    <section className="panel table-panel governance-table">{publications.loading ? <div className="panel-loading"><Spinner /></div> : !publications.data?.data.length ? <EmptyState title="Belum ada publikasi">Susun publikasi dari capaian OPD yang sudah disetujui.</EmptyState> : <div className="table-scroll"><table><thead><tr><th>Publikasi</th><th>Nomor</th><th>Versi</th><th>Item</th><th>Status</th></tr></thead><tbody>{publications.data.data.map((item) => { const open = async () => setSelected(await api<Publication>(`/publications/${item.id}`)); return <tr key={item.id} className="clickable-row" tabIndex={0} aria-label={`Buka publikasi ${item.title}`} onClick={open} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); void open(); } }}><td><div className="identity-cell"><span className="table-icon"><BadgeCheck /></span><span><strong>{item.title}</strong><small>{item.publication_key}</small></span></div></td><td>{item.publication_number}</td><td>{item.version_number}</td><td>{item.item_count}</td><td><Badge tone={item.status === "active" ? "success" : item.status === "draft" ? "warning" : "neutral"}>{statusLabel(item.status)}</Badge></td></tr>; })}</tbody></table></div>}{publications.data && <Pagination page={publications.data.meta.page} pageSize={publications.data.meta.page_size} totalItems={publications.data.meta.total_items} totalPages={publications.data.meta.total_pages} sortLabel="Terbaru dibuat" onChange={setPage} onPageSizeChange={(size) => { setPageSize(size); setPage(1); }} />}</section>
    {createOpen && <CreatePublication onClose={() => setCreateOpen(false)} onCreated={(item) => { setCreateOpen(false); setSelected(item); publications.reload(); }} />}
    {selected && <PublicationDetail publication={selected} permissions={user?.permissions ?? []} onClose={() => setSelected(null)} onChanged={(item) => { setSelected(item); publications.reload(); }} />}
  </>;
}

function CreatePublication({ onClose, onCreated }: { onClose(): void; onCreated(item: Publication): void }) {
  const [form, setForm] = useState({ publication_key: "RINGKASAN_TAHUNAN", publication_number: "", title: "", description: "", change_notes: "" });
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(""); try { onCreated(await api<Publication>("/publications", { method: "POST", mutation: true, body: jsonBody({ ...form, publication_key: form.publication_key.toUpperCase(), description: form.description || null, change_notes: form.change_notes || null }) })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Publikasi gagal dibuat."); } finally { setBusy(false); } };
  return <Modal title="Susun publikasi draft" onClose={onClose}>{error && <Notice tone="error">{error}</Notice>}<form className="form-stack" onSubmit={submit}><div className="form-grid"><label className="field"><span>Kunci publikasi</span><input value={form.publication_key} onChange={(e) => setForm({ ...form, publication_key: e.target.value.replace(/\s+/gu, "_") })} required /></label><label className="field"><span>Nomor publikasi</span><input value={form.publication_number} onChange={(e) => setForm({ ...form, publication_number: e.target.value })} required /></label></div><label className="field"><span>Judul</span><input value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} required /></label><label className="field"><span>Deskripsi</span><textarea rows={3} value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></label><label className="field"><span>Catatan perubahan</span><textarea rows={2} value={form.change_notes} onChange={(e) => setForm({ ...form, change_notes: e.target.value })} /></label><footer className="modal-actions"><button type="button" className="button secondary" onClick={onClose}>Batal</button><button className="button primary" disabled={busy}>{busy ? "Menyimpan…" : "Buat draft"}</button></footer></form></Modal>;
}

function PublicationDetail({ publication, permissions, onClose, onChanged }: { publication: Publication; permissions: string[]; onClose(): void; onChanged(item: Publication): void }) {
  const candidates = useAsync(() => api<{ data: PublicationCandidate[] }>("/publications/candidates"), []);
  const [chosen, setChosen] = useState<string[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const add = async () => { setBusy(true); setError(""); try { onChanged(await api<Publication>(`/publications/${publication.id}/items`, { method: "POST", mutation: true, body: jsonBody({ observation_ids: chosen }) })); setChosen([]); candidates.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Item gagal ditambahkan."); } finally { setBusy(false); } };
  const activate = async () => { if (!window.confirm("Aktifkan publikasi ini untuk dashboard pimpinan?")) return; setBusy(true); setError(""); try { onChanged(await api<Publication>(`/publications/${publication.id}/activate`, { method: "POST", mutation: true, body: jsonBody({ notes: "Diaktifkan melalui panel kurasi." }) })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Publikasi gagal diaktifkan."); } finally { setBusy(false); } };
  const draft = publication.status === "draft";
  return <Modal title={cleanDisplayText(publication.title)} onClose={onClose} wide>{error && <Notice tone="error">{error}</Notice>}<div className="publication-detail"><div className="detail-grid"><div><span>Nomor</span><strong>{publication.publication_number}</strong></div><div><span>Versi</span><strong>{publication.version_number}</strong></div><div><span>Status publikasi</span><strong>{statusLabel(publication.status)}</strong></div><div><span>Jumlah item</span><strong>{publication.items.length}</strong></div></div><section><h3>Capaian dalam publikasi</h3>{!publication.items.length ? <small>Belum ada capaian dipilih.</small> : <div className="chip-list publication-items">{publication.items.map((item) => <span key={item.id}>{item.indicator_code} - {item.period_label} - {formatPublishedValue(item.numeric_value, item.text_value, item.unit_symbol)}</span>)}</div>}</section>{draft && permissions.includes("publication.manage") && <section><h3>Pilih capaian yang telah disetujui</h3>{candidates.loading ? <Spinner /> : !candidates.data?.data.length ? <small>Belum ada kandidat capaian.</small> : <div className="candidate-list">{candidates.data.data.map((item) => <label key={item.observation_id}><input type="checkbox" checked={chosen.includes(item.observation_id)} onChange={(e) => setChosen((current) => e.target.checked ? [...current, item.observation_id] : current.filter((id) => id !== item.observation_id))} /><span><strong>{item.indicator_name}</strong><small>{item.organization_name} - {item.period_label} - {formatPublishedValue(item.numeric_value, item.text_value, item.unit_symbol)}</small></span></label>)}</div>}<button className="button secondary" disabled={busy || !chosen.length} onClick={add}><FilePlus2 />Tambahkan pilihan</button></section>}<footer className="detail-actions">{draft && permissions.includes("publication.activate") && <button className="button primary" disabled={busy || !publication.items.length} onClick={activate}><BadgeCheck />Aktifkan publikasi</button>}</footer></div></Modal>;
}
